Fix sphinx-build warnings
nest/nest-simulator pull request #1518
Opened 2020-04-17 14:41 UTC by sarakonradi

Fixes #1510

Currently, numerous warnings are emitted when generating HTML with Sphinx locally. 

The majority of these warnings are related to the model files and could disappear with the merge of #1374. This is because files (e.g., ``doc/models/create_models.rst``) that result in toctree warnings will anyhow be deleted in the other PR.

Given this information, the current PR has begun to tackle the other documentation-related warnings.

2020-06-16 13:04 UTC, terhorstd commented
this would be nice to have for nest-3, but is in no way mandatory. removing from milestone.

2020-11-09 22:34 UTC, jougs commented
During the current hackathon we decided that we should merge this as soon as possible to avoid endless merge conflicts and duplication of work in other branches. New warnings can then be addressed in new pull requests.

2020-11-09 22:40 UTC, jougs requested changes
Thanks for addressing these. I think we can even do without the second review by @stinebuu, so I'm removing the request for review.

2020-11-09 22:40 UTC, jougs commented on doc/contribute/mailing_list_guidelines.rst
>  =================================================
```suggestion
===============================================
```

2020-11-09 22:40 UTC, jougs commented on doc/contribute/templates_styleguides/example_template.rst
>  ==========================
```suggestion
=======================
```

2020-11-09 22:40 UTC, jougs commented on doc/contribute/templates_styleguides/pyapi_template.rst
>  =====================
```suggestion
===================
```

2020-11-09 22:40 UTC, jougs commented on doc/glossary.rst
> +
This should be moved to the beginning of the file. The way it is now breaks the formatting of the headline

2020-11-09 22:40 UTC, jougs commented on doc/glossary.rst
>  -------------------------------------------------------------
```suggestion
----------------------------------------------------------
```

2020-11-09 22:41 UTC, jougs commented
Also, please resolve the conflicts. Thanks!

2020-11-10 08:56 UTC, jougs approved these changes
Happy if Travis is. Thanks for taking care!

2020-11-10 13:25 UTC, merged