Add information on NEST and multiprocessing
nest/nest-simulator pull request #1622
Opened 2020-05-25 15:41 UTC by sarakonradi

This PR fixes #1581. 

It recommends against the use of Python's multiprocessing package on top of NEST's internal parallelization. I have also referenced [Ippen et al. (2017)](https://www.frontiersin.org/articles/10.3389/fninf.2017.00030/full), as suggested by @suku248. 

Perhaps we can update the section accordingly once we have a careful assessment about the interactions between NEST and multiprocessing?

2020-07-03 09:07 UTC, terhorstd commented on doc/guides/parallel_computing.rst
> +several ``ConnectLayers()`` calls simultaneously can lead to unpredictable results.
```suggestion
for example several ``Connect()`` calls simultaneously can interfere with the internal
parallelization and will likely lead to unpredictable/wrong results.
```

2020-07-21 12:15 UTC, terhorstd commented
@suku248, @diesmann do you still want to comment on these changes?

2020-09-15 22:48 UTC, jougs requested changes
I just have a small suggestion, but am fine otherwise. Many thanks!

2020-09-15 22:48 UTC, jougs commented on doc/guides/parallel_computing.rst
> +**Using Python's ``multiprocessing`` package with NEST may lead to unpredictable results!**
```suggestion
**Using Python's ``multiprocessing`` module with NEST may lead to unpredictable results!**
```

2020-09-16 06:13 UTC, sarakonradi commented
Done!

2020-09-16 08:13 UTC, terhorstd approved these changes
LGTM

2020-09-16 08:23 UTC, jougs approved these changes

2020-09-17 18:32 UTC, merged