Fix for first spike passing through "tsodyks2" synapse
nest/nest-simulator pull request #1672
Opened 2020-07-02 22:18 UTC by clinssen

I believe this fixes #957. @MatthiasKohler: could you confirm? See in particular the diff for ``models/tsodyks2_connection.h``.

It could be that the follow-up issue, #959, is too broad. I would suggest to close #959 if this PR is accepted.

2020-10-29 14:37 UTC, hakonsbm requested changes
Thanks for this fix. I have some small suggestions in the test.

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +            "weight": 1.            # initial weight
A bit much whitespace here
```suggestion
            "weight": 1.  # initial weight
```

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        assert np.all(np.abs(np.array(weight_reproduced_independently) - np.array(weight_by_nest)) < 1E-12)
Use an assert from [`numpy.testing`](https://numpy.org/doc/stable/reference/routines.testing.html) here to get more helpful messages in event of failure.

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        spike_detector = nest.Create("spike_detector")
Remember to change `spike_detector` to `spike_recorder` throughout.

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        all_spikes = nest.GetStatus(spike_detector, keys='events')[0]
We can write this simpler in NEST 3.0:
```suggestion
        all_spikes = spike_detector.events
```

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        pre_spikes = all_spikes['times'][all_spikes['senders'] == presynaptic_neuron.tolist()[0]]
With just a single node, the list of `global_id`s reduces to just the node ID with `.get()`.
```suggestion
        pre_spikes = all_spikes['times'][all_spikes['senders'] == presynaptic_neuron.get('global_id')]
```

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        times = wr.get("events", "times")
`times` isn't used anywhere.
```suggestion
```

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        A = 1.
I guess `A` here is defined in the article? It should probably be renamed, or at least commented, to better show what it represents. Same with `R_` below.

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        w = _initial_weight
This initial `w` isn't used, so it can probably be removed. And then `_initial_weight` can also be removed from the arguments.

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +                # A presynaptic spike occured now.
```suggestion
                # A presynaptic spike occurred now.
```

2020-10-29 14:37 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +                # Adjusting the current time to make it exact.
```suggestion
                # Adjusting the current time to make it exact.
```

2020-11-03 13:56 UTC, clinssen commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        spike_detector = nest.Create("spike_detector")
```suggestion
        spike_detector = nest.Create("spike_recorder")
```

2020-11-03 14:00 UTC, clinssen commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        spike_detector = nest.Create("spike_recorder")
```suggestion
        spike_recorder = nest.Create("spike_recorder")
```

2020-11-03 14:00 UTC, clinssen commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        nest.Connect(presynaptic_neuron + postsynaptic_neuron, spike_detector,
```suggestion
        nest.Connect(presynaptic_neuron + postsynaptic_neuron, spike_recorder,
```

2020-11-03 14:00 UTC, clinssen commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        all_spikes = spike_detector.events
```suggestion
        all_spikes = spike_recorder.events
```

2020-11-03 14:01 UTC, clinssen commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        # The detector is to save the randomly generated spike trains.
```suggestion
```

2020-11-03 14:07 UTC, clinssen commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        R_ = 1.
```suggestion
        R_ = 1.  # fraction of synaptic resources available for transmission
```

2020-11-09 09:38 UTC, stinebuu commented
@Nishant-codex This PR is now ready, please have a look and review!

2020-11-09 09:39 UTC, stinebuu commented
@clinssen The failing test is not Mac related(!), could you have a look?

2020-11-10 08:10 UTC, clinssen commented
@stinebuu: should be fixed now, thanks for pointing this out. Using the GitHub web editor to make more than a few single-line commits turned out to be too messy...

2020-11-12 13:18 UTC, hakonsbm requested changes
Looks pretty good, just a couple small (and somewhat nitpicky) things left.

2020-11-12 13:18 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        nest.SetKernelStatus({'resolution': self.resolution})
We should be consistent with using `'` or `"` for strings. Sorry I didn't see it sooner. `"` is mostly used here, so I've gone for that in my suggestions.
```suggestion
        nest.set_verbosity("M_WARNING")
        nest.ResetKernel()
        nest.SetKernelStatus({"resolution": self.resolution})
```

2020-11-12 13:18 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +            1,
A single node is the default for `Create()`, so I'm suggesting to remove this.
```suggestion
```

2020-11-12 13:18 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        wr = nest.Create('weight_recorder', 1)
```suggestion
        wr = nest.Create("weight_recorder")
```

2020-11-12 13:18 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        pre_spikes = all_spikes['times'][all_spikes['senders'] == presynaptic_neuron.get('global_id')]
```suggestion
        pre_spikes = all_spikes["times"][all_spikes["senders"] == presynaptic_neuron.get("global_id")]
```

2020-12-07 07:07 UTC, clinssen commented
Thanks, the new commit should address all this issues you raised. Single quotes look like they're more popular than double quotes in the existing Python source files, so I went with those.

2020-12-07 08:05 UTC, hakonsbm requested changes

2020-12-07 08:05 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +    '''
According to [PEP8](https://www.python.org/dev/peps/pep-0008/#string-quotes) triple-quoted docstrings should always use double quotes.

```suggestion
    """
```

2020-12-07 08:05 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +    '''
```suggestion
    """
```

2020-12-07 08:05 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        '''
```suggestion
        """
```

2020-12-07 08:05 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        '''
```suggestion
        """
```

2020-12-07 08:05 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        '''
```suggestion
        """
```

2020-12-07 08:05 UTC, hakonsbm commented on pynest/nest/tests/test_tsodyks2_connection.py
> +        '''
```suggestion
        """
```

2021-01-04 10:09 UTC, clinssen commented
Thanks for pointing this out, switched to double quotation marks instead.

2021-01-04 12:23 UTC, hakonsbm approved these changes
Thanks, looks good now.

2021-01-05 07:59 UTC, Nishant-codex approved these changes
I think these changes fix the problem.

2021-01-05 08:30 UTC, merged