Enable MUSIC tests and correct NEST testsuite results summary
nest/nest-simulator pull request #1766
Opened 2020-09-18 11:13 UTC by gtrensch

This PR reactivates the MUSIC tests. It also fixes an issue with incorrect entries in the NEST test suite results table that were encountered when forcing an error condition to test the correct behavior of the test suite.

_Resolved issues:_ #1557 
_Suggested reviewer:_ @heplesser

2020-09-21 09:09 UTC, hakonsbm requested changes
Thanks for fixing this! Looks good to me except for a couple lines with trailing whitespace.

2020-09-21 09:09 UTC, hakonsbm commented on testsuite/do_tests.sh
> +        # Copy everything to 'tmpdir'.
```suggestion
        # Copy everything to 'tmpdir'.
```

2020-09-21 09:09 UTC, hakonsbm commented on testsuite/do_tests.sh
> +        # Test failures and diagnostic information are also stored in the xml-report file
```suggestion
        # Test failures and diagnostic information are also stored in the xml-report file
```

2020-09-21 11:02 UTC, hakonsbm approved these changes

2020-09-24 15:13 UTC, heplesser approved these changes
Thanks, @gtrensch !

2020-09-24 15:13 UTC, merged