Remove `.colorize.rst`, which causes lots of errors and seems to be without function
nest/nest-simulator pull request #1795
Opened 2020-10-03 06:28 UTC by jd41

The current `conf.py` contains an epilog entry `include:: .colorize.rst`, which is appended to every rst file during the build process. This always tries to include that `.colorize.rst` from the same directory as the `rst` file being built, but because `.colorize.rst` only exists in the doc root directory, this causes ~300 errors.

If it was desired to include `.colorize.rst` everywhere, I think it would work by writing 'include:: /colorize.rst\n' everywhere (with a leading slash). But it seems that this file is not required or functional at all:
- A comment in the `.colorize.rst` file says it only works with `hacks.css`, but I can't find this file or a reference to it
- The only time a role defined there is used in the doc root directory (for other directories, it can't work anyway because the file is not included) is in `index.rst`, for "Introducing NEST 3.0". But this continues to look fine after removing the file.

This PR request removes the file.

2020-10-03 10:07 UTC, jd41 commented
Before anyone looks at this: Sorry, I hit the submit button too soon on this one. I am currently working on a fix and will then update the first message.

2020-10-03 11:22 UTC, jd41 commented
Updated now with new commits. I hope it works out now!

2020-11-10 08:32 UTC, steffengraber approved these changes
Tested and it works. Thanks Joris for this correction.

2020-11-11 15:19 UTC, sarakonradi requested changes
Thanks! It works. Please find my comments inline.

2020-11-11 15:19 UTC, sarakonradi commented on doc/colorize.rst
> +.. unfortunately, it still gets rendered as a HTML file, but it is not included in any toctree
```suggestion
.. It gets rendered as an HTML file but is not included in any toctree
```

2020-11-11 15:19 UTC, sarakonradi commented on doc/colorize.rst
> +.. In the NEST Doc, the content of hacks.css is included in _static/css/custom.css
```suggestion
.. In the NEST documentation, the content of hacks.css is included in _static/css/custom.css
```

2020-11-19 07:05 UTC, heplesser commented
@jd41 With #1839 and #1852, we fixed several problems in the Travis setup. Please merge master into the branches in your PRs to ensure that testing will work properly on all systems.

2021-02-02 13:06 UTC, jessica-mitchell commented
Closing and will be addressed by @jessica-mitchell

2021-02-02 13:06 UTC, closed without merging