Create Structural_Plasticity_Node separate from Archiving_Node
nest/nest-simulator pull request #1820
Opened 2020-10-30 14:10 UTC by clinssen

This is a refactoring that helps to separate concerns between Archiving_Node, and a new class, Structural_Plasticity_Node. The former manages spiking history and internal state in a "history" buffer, typically for the sake of STDP synapses. The latter manages a calcium concentration and a map of "synaptic elements".

Because we want to make NESTML generated code independent of the Archiving_Node, we would like NESTML neurons to not inherit from Archiving_Node any longer, but directly from Node. The replacement functionality would be generated by NESTML. However, we are not concerned with the structural plasticity code, and would like to leave this undisturbed. For this reason, it helps a lot if these are separated into two classes, and this is easily possible because they don't have many mutual dependencies.

So we propose to change the inheritance diagram from ``Node ← Archiving_Node`` to ``Node ← Structural_Plasticity_Node ← Archiving_Node``. NESTML neurons would then inherit directly from Structural_Plasticity_Node, thereby avoiding Archiving_Node. No further changes are required to the existing NEST models, which continue to inherit (typically) from Archiving_Node.

@sdiazpier: I know that you were working on a refactoring of the structural plasticity system into a user module. I hope that this PR does not cause a lot of overhead for you in doing that. I've strived for the minimal change to take the structural plasticity components out, but welcome your feedback!

2020-10-30 14:36 UTC, heplesser commented
@clinssen Two comments:
- If you no longer inherit from archiving node, how will the NESTML neurons support STDP?
- If you refactor this, I'd much appreciate if you'd use the opportunity to replace our hybrid camel-underscore-naming with pure camel: `ArchivingNode`, `StructuralPlasticityNode`.

2020-10-31 08:36 UTC, clinssen commented
Thanks for your comments! NESTML will generate its own code for this part of the infrastructure. Archiving_Node does not offer any flexibility for different types of plasticity: it is not templatised with a histentry type, even though different types of neurons have different archiving requirements (e.g. whether a triplet-STDP type trace is needed, a vanilla all-to-all STDP trace, extra traces for the Clopath synapse, etc.) See also https://github.com/nest/nest-simulator/blob/master/nestkernel/histentry.h.

The NESTML generated code will make Archiving_Node obsolete, as well as the histentry structs, and we should probably remove the virtual declarations that are specific to STDP, Clopath and Urbancyk plasticity from the Node class as well (see from https://github.com/nest/nest-simulator/blob/a1623206604023bbba22d486e48997d09bd93d76/nestkernel/node.h#L672 onwards). But that's for a future PR.

The underscores I will address as soon as our Travis MacOS environment is fixed.

2020-11-03 09:07 UTC, heplesser commented
@clinssen Thanks for the explanation, that makes a lot of sense! Does this mean one could make a compile-time decision that I never want plasticity and so can build all neuron models without support for it? Would the same also apply for structural plasticity? I guess I am just wondering why we no longer need a "plasticity node" class (aka Archiving_Node) but still need a "structural plasticity node" class with your new NESTML-based design.

2020-11-03 09:27 UTC, clinssen commented
Indeed, if no plasticity is used in the network, then no spike archiving is needed and will not be compiled in (that is, the code will not even be generated in the neuron C++ file). This will tie in well with the just-in-time build strategy that we proposed at the last NEST Conference (but already applies even without JIT, that is, when NESTML is invoked manually).

Structural plasticity is a rather different beast, and for NESTML we would like to remain agnostic to this for now. Hence, we propose to split off the code related to structural plasticity from the ArchivingNode, so that it can be left untouched as much as possible. I believe @sdiazpier has longer-term plans to turn this into a user module, which would then ultimately also replace the StructuralPlasticityNode.

2020-11-09 15:55 UTC, heplesser requested changes
@clinssen Overall, this looks good to me overall, but see my inline comments, especially on the class name and `last_spike_`.

2020-11-09 15:55 UTC, heplesser commented on nestkernel/structural_plasticity_node.cpp
> +// member functions for Structural_Plasticity_Node
This comment is superfluous.

2020-11-09 15:55 UTC, heplesser commented on nestkernel/structural_plasticity_node.cpp
> +* ---------------------------------------------------------------- */
This type of comment is not needed here, remove.

2020-11-09 15:55 UTC, heplesser commented on nestkernel/structural_plasticity_node.h
> + * a node which archives spike history for the purposes of
Single line summary starting with capital letter. Details can follow in a separate paragraph.

2020-11-09 15:55 UTC, heplesser commented on nestkernel/structural_plasticity_node.h
> +class Structural_Plasticity_Node : public Node
Please change to `StructuralPlasticityNode`—no need to repeat errors of the past ;).

2020-11-09 15:55 UTC, heplesser commented on nestkernel/structural_plasticity_node.h
> +  double last_spike_;
Looks to me as if we have `last_spike_` now in `StructuralPlasticityNode` *and*  in `Archiving_Node`. Please make sure that it appears only one, presumably `Archiving_Node`.

2020-11-09 15:55 UTC, heplesser commented on nestkernel/structural_plasticity_node.h
> +   */
This comment is no longer relevant, since we are now in SPN.

2020-11-09 15:55 UTC, heplesser commented on nestkernel/structural_plasticity_node.h
> +  // Time of the last update of the Calcium concentration in ms
Turn comment and subsequent comments into proper Doxygen comments.

2020-11-09 20:36 UTC, clinssen commented
Thanks for the detailed review! The new commits should address all your comments. Of course renaming the Archiving_Node bumped us up from 5 to 125 changed files. ``test_jonke_synapse.py`` was corrected for DOS to Unix line endings in the process, which is why it shows up in the diff.

2020-11-10 09:29 UTC, heplesser approved these changes
@clinssen Thanks for even fixing historical flaws ;). I have one little thing I'd like to see fixed in a comment, but will approve now already.

2020-11-10 09:29 UTC, heplesser commented on nestkernel/structural_plasticity_node.h
> +   * Value of the calcium concentration [Ca2+] at Ca_t_. Intracellular calcium
Split into single-line short description followed by details.

2020-11-10 10:54 UTC, sdiazpier approved these changes
Dear @clinssen  thanks a lot for this PR. It looks great from my side and clean cut. No further comments from my side at this moment.

2020-11-10 12:58 UTC, jougs commented
There is still [on failing MPI test](https://travis-ci.org/github/nest/nest-simulator/jobs/742663955#L7816).

2020-11-11 11:26 UTC, clinssen commented
@jougs: thanks for being so observant! Pulling latest master fixed that issue, and we also spun off #1837 to point out that the number of warnings generated by the C++ build itself is now checked against a hard-coded number. It should be ready for merge now.

2020-11-11 12:41 UTC, merged