Add documentation about our CI pipeline
nest/nest-simulator pull request #1837
Opened 2020-11-11 09:12 UTC by clinssen

Following discussion during the NEST Hackathon at 2020-11-11: confusion on my part on what was causing the CI to fail, turned out to be the addition of hardcoded expected number of compiler warnings in #1796. This adds some documentation about NEST-specific parts of CI.

2020-12-11 16:30 UTC, sarakonradi requested changes
Thanks for adding the documentation! Here are some minor comments.

2020-12-11 16:30 UTC, sarakonradi commented on doc/contribute/index.rst
> +An explanation of our continuous integration pipeline can be found under :doc:`ci.rst`.
```suggestion
An explanation of our continuous integration pipeline can be found under :doc:`ci.`.
```

2020-12-11 16:30 UTC, sarakonradi commented on doc/contribute/ci.rst
> +   - pycodestyle is used to statically check Python code. A few errors are intentionally ignored, defined in the variable ``PEP8_IGNORES`` in `extras/static_code_analysis.sh <https://github.com/nest/
```suggestion
   - pycodestyle is used to statically check Python code. A few errors are intentionally ignored, defined in the variable ``PEP8_IGNORES`` in `extras/static_code_analysis.sh <https://github.com/nest/nest-simulator/blob/master/extras/static_code_analysis.sh>`_. Again, the maximum line length is 120 characters.
```

2020-12-11 16:30 UTC, sarakonradi commented on doc/contribute/ci.rst
> +In order to address this problem, a `Travis <http://travis-ci.org/>`_ Continuous Integration (CI) service has been set up, which allows for regular testing of changes that are getting into the tree a
```suggestion
In order to address this problem, a `Travis <http://travis-ci.org/>`_ Continuous Integration (CI) service has been set up, which allows for regular testing of changes that are getting into the tree and timely reporting of identified problems. This way, issues will be discovered earlier and the amount of efforts to fix them significantly decreased.
```

2020-12-11 17:03 UTC, clinssen commented
Cheers, no comments from me, all three suggestions merged!

2021-02-15 14:27 UTC, terhorstd approved these changes
LGTM :+1: 
Thanks, @clinssen!

2021-02-18 13:31 UTC, sarakonradi requested changes

2021-02-18 13:31 UTC, sarakonradi commented on doc/contribute/index.rst
> +An explanation of our continuous integration pipeline can be found under :doc:`ci.`.
```suggestion
An explanation of our continuous integration pipeline can be found under :doc:`ci`.
```

2021-02-18 13:31 UTC, sarakonradi commented on doc/contribute/index.rst
> +An explanation of our continuous integration pipeline can be found under :doc:`ci.`.
Spotted an extra full stop. Now the link should work!

2021-02-18 13:34 UTC, clinssen commented
Oops, cheerio!

2021-02-18 15:16 UTC, sarakonradi approved these changes
Awesome, thanks!

2021-02-26 09:58 UTC, merged