Update documentation on parameter dictionaries with lists
nest/nest-simulator pull request #1848
Opened 2020-11-13 11:41 UTC by stinebuu

I have updated the documentation about parameter dictionaries with lists when creating nodes, or when setting parameters with `SetStatus()` and `set()`. Docstrings are updated, the neuron tutorial is updated a little, and I have added the information in the NEST 2 to NEST 3 transistion guide.

This fixes #1813

2020-11-13 13:58 UTC, sarakonradi requested changes
Thanks for addressing #1813! Here are a few minor suggestions.

2020-11-13 13:58 UTC, sarakonradi commented on doc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

2020-11-13 13:58 UTC, sarakonradi commented on doc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
> +lists of dictionaries. Note that this is still possible.
```suggestion
list of dictionaries. This is still possible.
```

2020-11-13 13:58 UTC, sarakonradi commented on doc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
> +The values in the single dictionary can also be single values, the value will
```suggestion
The values in the single dictionary can also be single values; the value will
```

2020-11-13 13:58 UTC, sarakonradi commented on doc/guides/nest2_to_nest3/nest2_to_nest3_overview.rst
> +then be applied to each node. You can mix and match as you want, the dictionary
```suggestion
then be applied to each node. You can mix and match as you want; the dictionary
```

2020-11-13 13:58 UTC, sarakonradi commented on doc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +in one go. To do this supply a dictionary with lists the same length
```suggestion
in one go. To do this, supply a dictionary with lists the same length
```

2020-11-13 13:58 UTC, sarakonradi commented on doc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +contain single values, these will then be applied to each node.
```suggestion
contain single values, which will then be applied to each node.
```

2020-11-30 15:45 UTC, terhorstd approved these changes
LGTM :+1:

2020-12-03 14:43 UTC, sarakonradi approved these changes
Thanks!

2020-12-09 09:06 UTC, merged