Fix Wundefined-var-template warnings
nest/nest-simulator pull request #1851
Opened 2020-11-16 09:35 UTC by hakonsbm

Moved definitions of static members from layer_impl.h to layer.h to fix `Wundefined-var-template` warnings when compiling with Clang.

2020-11-16 11:46 UTC, heplesser commented
@hakonsbm Thanks, it compiles without warning with Apple Clang 12 as well now. The only remaining warnings are from pynestkernel/Cython-generated code, so not really our fault:
```
[ 99%] Building CXX object pynest/CMakeFiles/pynestkernel.dir/pynestkernel.cxx.o
/Users/plesser/NEST/code/bld_clang_mpi/pynest/pynestkernel.cxx:28238:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
  0, /*tp_print*/
  ^
/Users/plesser/opt/miniconda3/envs/nest_dev/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
    Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
    ^
/Users/plesser/opt/miniconda3/envs/nest_dev/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
```
Since we only compile cython-generated code in pynestkernel, it made me wonder if we can drop most of the compiler warning flags when building pynestkernel. But that would be an other issue, I suppose.

2020-11-16 11:47 UTC, heplesser approved these changes
Approving conditional on all tests passing.

2020-11-18 06:24 UTC, heplesser approved these changes
@hakonsbm Could you take a look at https://github.com/nest/nest-simulator/pull/1852/commits/e322613d56265fa8a698218e33abf09e8106f82f by @jougs solving this problem in a slightly different (and I think even better) way? It is already merged, so this PR may be obsolete now.

2020-11-18 06:25 UTC, heplesser requested changes
See previous post, I meant to block until you have compared with the change in #1852.

2020-11-18 07:50 UTC, hakonsbm commented
@heplesser I think it would have been cleaner to have the definitions of the static members in the same header file as the class definition. But seeing as e322613 is already merged, I'll close this.

2020-11-18 07:50 UTC, closed without merging

2020-11-18 10:41 UTC, jougs commented
Sorry for fixing this differently in #1852, I was not actually aware of this PR when I did that.