Remove unused lines from the part 1 tutorial document.
nest/nest-simulator pull request #1867
Opened 2020-12-07 14:53 UTC by pnbabu

import of SciPy and scikit-learn are not required for the part 1 tutorial, removing them.

2021-01-04 10:13 UTC, clinssen commented
As these are examples of other packages that *can* (but do not have to) be imported, would it be better to change the formulation of the text, rather than remove the import statements?

For example, instead of saying

"It should be noted, however, that certain external packages must be imported before importing nest. These include scikit-learn and SciPy."

could we say something along the lines of

"In case other packages are required, such as scikit-learn and SciPy, these need to be imported *before* importing nest."

2021-02-03 10:36 UTC, jessica-mitchell requested changes
I just have a couple of minor changes - see inline for suggestions.

2021-02-03 10:36 UTC, jessica-mitchell commented on doc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
> +In case other python packages are required, such as `scikit-learn <http://scikit-learn.org/stable/index.html>`_
```suggestion
In case other Python packages are required, such as `scikit-learn <http://scikit-learn.org/stable/index.html>`_
```

2021-02-03 10:36 UTC, jessica-mitchell commented on doc/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.rst
> +and `SciPy <https://www.scipy.org/>`_, they need to be imported before importing nest.
```suggestion
and `SciPy <https://www.scipy.org/>`_, they need to be imported *before* importing NEST.
```

2021-02-04 07:55 UTC, jessica-mitchell approved these changes
Thanks @pnbabu! looks good

2021-02-04 07:59 UTC, merged