Fix nest-server not starting with apt-installed uwsgi
nest/nest-simulator pull request #1873
Opened 2020-12-14 12:27 UTC by Mike2208

See #1872.

This PR adds `--plugin python3` to the uwsgi commands in `extras/nest-server`. With this, the `nest-server` command works even if uwsgi was installed via apt and not pip

2021-02-05 11:33 UTC, babsey requested changes
Thanks. It works on my side. 
However, I made some suggestions in specific lines to avoid crossing max line length.

But in general, LGTM.

2021-02-05 11:33 UTC, babsey commented on extras/nest-server
> +      uwsgi --plugin python3 --module nest.server:app --http-socket $HOST:$PORT --uid $USER --daemonize "/tmp/nest-server.log"
```suggestion
      uwsgi \
        --plugin python3 \
        --module nest.server:app \
        --http-socket $HOST:$PORT \
        --uid $USER \
        --daemonize "/tmp/nest-server.log"
```

2021-02-05 11:33 UTC, babsey commented on extras/nest-server
> +      uwsgi --plugin python3 --module nest.server:app --http-socket $HOST:$PORT --uid $USER
```suggestion
      uwsgi \
        --plugin python3 \
        --module nest.server:app \
        --http-socket $HOST:$PORT \
        --uid $USER
```

2021-02-09 07:36 UTC, stinebuu commented
@Mike2208 Could you also merge master into your branch? We have had some problems with Travis, and this has been fixed after you opened your PR. Thanks!

2021-02-24 13:03 UTC, stinebuu commented
@Mike2208 Do you have time to look at the comments?

2021-04-08 13:13 UTC, hakonsbm commented
Replaced by #1998.

2021-04-08 13:13 UTC, closed without merging