Add synapse_label and receptor_type support to spatial connections
nest/nest-simulator pull request #1876
Opened 2020-12-15 15:52 UTC by hakonsbm

Implements connection with specified receptor type or synapse label when using spatial parameters, also for collocated synapses.

2020-12-16 07:26 UTC, stinebuu commented
@hakonsbm `receptor_type` already work with `CollocatedSynapses` do they not?

2020-12-16 08:18 UTC, hakonsbm commented
@stinebuu Yes, this is only for spatial connections. However, I see that I forgot the test for `receptor_type` with `CollocatedSynapses`, so I'll add that.

2021-01-13 09:34 UTC, stinebuu commented
We should wait with this until the problems in #1868 is addressed.

2021-02-01 09:41 UTC, stinebuu approved these changes
I am happy with these changes. I think we in the future should change the spatial connect to take all synapse specific parameters, like is done in `conn_builder`, but that is not something that should be done in this PR.

2021-02-01 11:03 UTC, stinebuu commented
@hakonsbm could you merge master to make Travis happy?

2021-02-01 12:13 UTC, heplesser reviewed
@hakonsbm The code looks correct to me, but confusing, due to the double-up of code for individual and collocated synapses. I think the code would become clearer by first extracting all parameters relevant to the connection rule, then to check if there is a `synapse_params` (i.e., collocated synapses) and handling that, and then handling the case of a single synapse specification. Maybe extracting the synapse params can then be delegate to a helper function to avoid code duplication. Something along the line of (very pseudocode here)
```c++
if d->known("synapse_params")
{
  param_dicts_.resize(...);
  for ( auto sp : synapse_params )
      extract_params(sp);
}
else
{
  param_dicts_.resize(1);
  extract_params(d);
}
```

2021-02-03 15:25 UTC, hakonsbm commented
@heplesser Done!

2021-02-03 21:06 UTC, heplesser requested changes
@hakonsbm Thanks, looks much better now. Just to small remarks.

2021-02-03 21:06 UTC, heplesser commented on nestkernel/connection_creator.cpp
> +  }
I think with `updateValue()` this can be simplified to the following. I also exploit here that we are in the constructor, so we can change the member variable directly, because the object will be destroyed if the value is negative, no need for a temporary local variable.

```c++
if ( updateValue< long >(dict, names::number_of_connections, number_of_connections_ )
{
  if ( number_of_connections_ < 0 )
  {
    throw BadProperty( "Number of connections cannot be less than zero." );
  }
} 
```

2021-02-04 09:40 UTC, hakonsbm commented on nestkernel/connection_creator.cpp
> +  }
But `number_of_connections_` is of type `size_t`, so updating it directly will make it impossible to detect if a negative number is specified.

2021-02-04 09:47 UTC, hakonsbm commented on nestkernel/connection_creator.cpp
> +  auto store_bool_if_known = [&dict]( bool& target, const Name& name ) -> void
I suspected that there was a function for this. I've updated the calls now.

2021-02-04 11:46 UTC, heplesser commented on nestkernel/connection_creator.cpp
> +  }
Good point, but difficult to see from the code. Could you add a brief comment?

2021-02-04 14:21 UTC, hakonsbm commented on nestkernel/connection_creator.cpp
> +  }
@heplesser Done.

2021-02-04 16:05 UTC, heplesser approved these changes
@hakonsbm Nice work! Approving conditional on Travis passing.

2021-02-05 07:41 UTC, merged