Fix for printing empty SynapseCollection
nest/nest-simulator pull request #1886
Opened 2021-01-11 12:19 UTC by hakonsbm

Printing an empty SynapseCollection will no longer raise a `TypeError`, but print
```
 source   target   synapse model   weight   delay 
-------- -------- --------------- -------- -------
```
I'm also open for more explicit representations of an empty SynapseCollection.

Fixes #1884

2021-01-13 08:52 UTC, stinebuu requested changes
Thanks, I have a couple of suggestions

2021-01-13 08:52 UTC, stinebuu commented on pynest/nest/lib/hl_api_types.py
> +            d_len = len(d_h) + 2
Maybe something like this instead, to shorten somewhat?
```suggestion
        else:
            src_len = max(len(src_h) + 2, floor(log(max(srcs), 10)))
            trg_len = max(len(trg_h) + 2, floor(log(max(trgt), 10)))
            sm_len = max(len(sm_h) + 2, len(max(s_model, key=len)))
        w_len = len(w_h) + 2
        d_len = len(d_h) + 2
```

2021-01-13 08:52 UTC, stinebuu commented on pynest/nest/lib/hl_api_types.py
> +            srcs = params['source']
Maybe use `srcs = params['source'] if len(params) != 0 else []` to shorten? And the same for all the others. Now we have 2 `if` sentences to define `srcs` etc. (There is also an `if isinstance (srcs, int)` just below this.

2021-01-13 08:55 UTC, stinebuu commented
Also, I remember fixing the `boarder` thing, but apparently I never committed that, good we get to fix it now!

2021-01-19 12:02 UTC, stinebuu approved these changes
Thanks!

2021-01-27 20:30 UTC, jougs reviewed
I'm fine with the code as is, but wonder if we instead should print something more friendly like
```
The synapse collection does not contain any connections!
```
@sarakonradi, @jessica-mitchell: what does the docteam think about this?

2021-01-28 06:39 UTC, heplesser commented
> I'm fine with the code as is, but wonder if we instead should print something more friendly like
> 
> ```
> The synapse collection does not contain any connections!
> ```

I agree with @jougs, but would replace the exclamation mark with a full stop :).

2021-02-01 13:03 UTC, jougs approved these changes
Thanks!

2021-02-01 13:04 UTC, merged