Remove all mentions of spike multiplicity from user documentation
nest/nest-simulator pull request #1916
Opened 2021-02-04 22:24 UTC by heplesser

Spike multiplicity is an internal implementation detail of NEST and should thus not be mentioned in user-facing documentation. In some cases, this PR moves such documentation to developer docs (doxygen docstrings) or removes it entirely where that seemed the better choice.

The PR also adds user-directed admonitions to documentation for binary neurons and improves docstring formatting.

@ddahmen Could you look at the binary neuron and population generator documentation and check it for correctness of content?

2021-02-18 13:16 UTC, sarakonradi requested changes
Thanks for updating the documentation! I have a few minor comments - please see inline.

2021-02-18 13:16 UTC, sarakonradi commented on models/ginzburg_neuron.h
> +   As a binary neuron, the ``ginzburg_neuron``, the user must
```suggestion
   As the ``ginzburg_neuron`` is a binary neuron, the user must
```

2021-02-18 13:16 UTC, sarakonradi commented on models/ginzburg_neuron.h
> +   #. At most one connection must be created between any pair of
```suggestion
   #. At most, one connection must be created between any pair of
```

2021-02-18 13:16 UTC, sarakonradi commented on models/mcculloch_pitts_neuron.h
> +The `mcculloch_pitts_neuron` is an implementation of a binary
```suggestion
The ``mcculloch_pitts_neuron`` is an implementation of a binary
```

2021-02-18 13:16 UTC, sarakonradi commented on models/mcculloch_pitts_neuron.h
> +   As a binary neuron, the ``mcculloch_pitts_neuron``, the user must
```suggestion
   As the ``mcculloch_pitts_neuron`` is a binary neuron, the user must
```

2021-02-18 13:16 UTC, sarakonradi commented on models/mcculloch_pitts_neuron.h
> +   #. At most one connection must be created between any pair of
```suggestion
   #. At most, one connection must be created between any pair of
```

2021-02-18 13:16 UTC, sarakonradi commented on models/pp_pop_psc_delta.h
> +   population model implementation is now available, see ``gif_pop_psc_exp``.
```suggestion
   population model implementation is now available (see :doc:`gif_pop_psc_exp <gif_pop_psc_exp>`).
```

2021-02-18 16:24 UTC, heplesser commented on models/binary_neuron.h
> + * larger 1 are delivered consecutively, also in a parallel setting.
Yes.

2021-02-18 16:25 UTC, heplesser commented on models/erfc_neuron.h
> +   #. At most one connection must be created between any pair of
I will reword here.

2021-02-18 16:28 UTC, heplesser commented on models/ginzburg_neuron.h
> +   #. At most one connection must be created between any pair of
See above.

2021-02-18 16:29 UTC, heplesser commented on models/mcculloch_pitts_neuron.h
> +   #. At most one connection must be created between any pair of
See above.

2021-02-18 16:32 UTC, heplesser commented
@sarakonradi Thanks for your feedback. Could you check if all is fine now?

2021-02-19 11:20 UTC, sarakonradi commented on models/erfc_neuron.h
> +   #. At most one connection must be created between any pair of
Great, it reads much better now.

2021-02-19 11:25 UTC, sarakonradi reviewed
Thanks for applying the suggestions and rewording the admonition. I have one minor comment left for ``gif_pop_psc_exp.h``. Could you please check?

2021-02-19 11:29 UTC, heplesser commented on models/gif_pop_psc_exp.h
>  tau_sfa.
Done.

2021-02-19 11:29 UTC, heplesser commented
@ddahmen Could you take a look as well?

2021-02-19 12:55 UTC, ddahmen approved these changes
Thank you very much @sarakonradi and @heplesser !
Everything looks very good!

2021-02-22 09:15 UTC, sarakonradi approved these changes
Looks good to me, many thanks!

2021-02-22 10:48 UTC, merged