Remove SLI examples in model documentation
nest/nest-simulator pull request #1936
Opened 2021-02-22 14:02 UTC by jessica-mitchell

I stumbled upon a couple of SLI examples that are still lingering in the model documentation - in spike_generator and music_rate_out_proxy specifically.
This PR simply removes them, and fixes up a bit of formatting.

2021-02-23 07:22 UTC, heplesser requested changes
@jessica-mitchell The rules for moving spikes times to grid time points in `spike_detector` are not trivial. The examples given in the code provide valuable information which should not get lost. The principles are described in the remaining documentation, but they become a lot easier to understand with the examples in place. How about converting the SLI examples to corresponding PyNEST examples?

2021-02-23 19:08 UTC, jessica-mitchell commented
@heplesser I converted the SLI examples to PyNEST, please take a look that I did not bugger the syntax and it makes sense in the context of PyNEST.

2021-02-24 11:26 UTC, heplesser requested changes
@jessica-mitchell Thanks for the PyNEST example. There is one little error for which I added a suggestion. One general question: Have we made a decision concerning the use of single vs double quotes in Python code?

2021-02-24 11:26 UTC, heplesser commented on models/spike_generator.h
> +     nest.SetStatus("spike_generator",
```suggestion
     nest.Create("spike_generator",
```

2021-02-24 11:46 UTC, jessica-mitchell commented
@heplesser I dont remember for certain how discussions ended- but i think we were leaning towards double quotes.

2021-02-24 11:47 UTC, heplesser approved these changes

2021-02-26 14:28 UTC, sarakonradi requested changes
@jessica-mitchell Thanks! I have added a few minor suggestions inline.

2021-02-26 14:28 UTC, sarakonradi commented on models/spike_generator.h
> +100). Then, any spike times set, at this time, must be later than step 100.
```suggestion
100). Then, any spike times set at this time must be later than step 100.
```

2021-02-26 14:28 UTC, sarakonradi commented on models/spike_generator.h
> +Assume we have simulated 10.0 ms and simulation times is thus 10.0 (step
Do you mean ``simulation time``?

2021-02-26 14:28 UTC, sarakonradi commented on models/spike_generator.h
> +Assume that NEST works with default resolution (step size) of 0.1 ms
```suggestion
Example:

Assume that NEST works with default resolution (step size) of 0.1 ms
```

2021-03-03 09:58 UTC, jessica-mitchell commented on models/spike_generator.h
> +Assume we have simulated 10.0 ms and simulation times is thus 10.0 (step
```suggestion
Assume we have simulated 10.0 ms and simulation time is thus 10.0 (step
```

2021-03-03 10:02 UTC, jessica-mitchell commented
@sarakonradi I've accepted all your suggestions

2021-03-03 10:07 UTC, sarakonradi approved these changes

2021-03-03 11:09 UTC, heplesser commented
This PR changes only comments; the failing test is related to #1944 and definitely not related to this PR. I will this merge now.

2021-03-03 11:09 UTC, merged