Hike Boost minimum version to 1.69
nest/nest-simulator pull request #1937
Opened 2021-02-23 08:26 UTC by heplesser

This is due to change in Boost sort algoirhtm with version 1.69, see #1502. 

CI uses 1.72 since #1502 and current version is 1.75, so 1.69 is a conservative choice.

2021-02-23 10:26 UTC, hakonsbm requested changes

2021-02-23 10:26 UTC, hakonsbm commented on cmake/ProcessOptions.cmake
> +    # Require Boost versoin >=1.69.0 due to change in Boost sort
```suggestion
    # Require Boost version >=1.69.0 due to change in Boost sort
```

2021-02-23 11:30 UTC, hakonsbm approved these changes

2021-03-03 10:16 UTC, terhorstd approved these changes
LGTM :+1:

2021-03-03 10:16 UTC, merged