Only static code analysis in Travis Build Matrix
nest/nest-simulator pull request #1978
Opened 2021-03-15 11:37 UTC by lekshmideepu

Except the status code analysis check, removed all the other matrix builds from Travis CI. Currently the static checks for changed files are not implemented in our githubactions.

2021-03-15 11:57 UTC, heplesser requested changes
@lekshmideepu Thank you! As long as Github does not actually perform the static analysis, would you remove that from the Github actions matrix to avoid confusing false positives? And one tiny suggestion, see below.

2021-03-15 11:57 UTC, heplesser commented on .travis.yml
> +   - ./extras/travis_build.sh 2>&1 | tee travis_build.sh.log
Add a newline.
```suggestion
   - ./extras/travis_build.sh 2>&1 | tee travis_build.sh.log
   
```

2021-03-15 12:10 UTC, lekshmideepu commented
@heplesser : Thanks for taking a look. I have just addressed both your comments.

2021-03-15 13:10 UTC, heplesser approved these changes
Thanks!

2021-03-16 13:27 UTC, jougs approved these changes
LGTM! Thanks!

2021-03-16 13:27 UTC, merged