Remove hill_tononi_Vp example
nest/nest-simulator pull request #1981
Opened 2021-03-17 14:53 UTC by heplesser

This PR removes the example and adds instead links to the scientifically validated implementation of the full Hill-Tononi model by Ricardo Murphy and colleagues.

This fixes #982.

2021-03-17 14:57 UTC, heplesser commented
@jessica-mitchell I have a technical problem here: https://github.com/heplesser/nest-simulator/blob/001e65a623cd0a5341c21b41ac8c1a85e2ff321e/models/ht_neuron.h#L98-L99 .

With the line break as it is now, our clang-format is happy, but Sphinx does not render the link properly. If I put everything on one line, Sphinx renders the link properly, but clang-format complains. Any ideas how to solve this?

2021-03-18 10:36 UTC, jessica-mitchell commented
@heplesser When you have a bullet list, the second line has to line up with the first - so it looks like this
```
* `very long text for link
  <link>`_
```

2021-03-18 11:10 UTC, heplesser commented
> @heplesser When you have a bullet list, the second line has to line up with the first - so it looks like this
> 
> ```
> * `very long text for link
>   <link>`_
> ```


Thanks for the hint, fixed!

2021-03-19 09:10 UTC, jessica-mitchell requested changes
@heplesser Thanks for updating this. I noticed the links to the jupyter notebooks in model_details are broken, which is relevant to this PR. It would be great if that could be fixed here - two things have to change:  re-add extension 'nbsphinx' to conf.py (somewhere along the way since #1949  'nbsphinx' it was removed)  and move the model_details directory to userdoc/.

2021-03-19 09:10 UTC, jessica-mitchell commented on doc/model_details/HillTononiModels.ipynb
> +    "In what follows, I will refer to the original paper as [HT05].\n",
```suggestion
    "In what follows, we will refer to the original paper as [HT05].\n",
```

2021-03-19 09:49 UTC, heplesser commented
@jessica-mitchell Done! I noticed that in earlier versions of `conf.py`, in addition to `nbsphinx` there was also `breathe`, which is no longer there. Is it no longer needed?

2021-03-19 10:39 UTC, heplesser commented
@jessica-mitchell I struggle with ensuring proper installation of the model_details directory after moving it to userdocs. Could you give me a pointer to a version where model_details was in userdocs and got installed? I just pushed an update that solves some problems but **does not install the notebooks**.

2021-03-19 12:15 UTC, jessica-mitchell commented
@heplesser I'm not sure I fully understand what you mean with not installing the notebooks? From your latest commit, I can open the notebooks in the documentation so they're visible on the browser, and I can open them from the console in jupyter-notebook (from `install/share/doc/nest/html/model_details/`).  I moved `model_details `because it seemed more logical to put it into `userdoc/` and the relative path link in the models would be correct. But it could very well be that I broke something - I am still trying to understand all the consequences of this new build workflow for documentation. 

as for breathe - I'm pretty sure we are not using it, that  was replaced by Dennis' extractor script for models.

2021-03-19 15:40 UTC, heplesser commented
@jessica-mitchell Sorry, my mistake. I had forgotten to run `make html` before `make install`. All fine now :).

2021-03-22 07:48 UTC, jessica-mitchell approved these changes
I think this looks good, thanks @heplesser !

2021-03-22 08:39 UTC, heplesser commented
Documentation change, therefore merging after single review.

2021-03-22 08:39 UTC, merged