Move developer space content into docs on master branch
nest/nest-simulator pull request #1995
Opened 2021-03-30 10:56 UTC by clinssen

Content on the "developer space" pages lives on a separate branch, which adversely impacts its maintainability (for us developers) and discoverability (for users). Much of the content there is outdated, no longer relevant and/or superseded by content that is already on ReadTheDocs.

The remaining content that seems useful is hereby transferred into the ReadTheDocs pages. The "developer space" can be completely removed after merging this PR, by removing the ``gh-pages`` branch on this repository.

2021-04-13 17:54 UTC, jessica-mitchell commented
thanks @clinssen for this PR! 

I think this PR covers the files leftover from #1659, and so that issue could be resolved, correct?

For the extension modules - do we want to keep the file, considering  we have the extension module repository in development? 

Also, just a note that I think further re-arranging of some of these files will be necessary, but I'm happy to have them moved into the documentation!

2021-04-13 20:36 UTC, clinssen commented
Thanks for linking #1659! Yes, this PR (repeating the verbiage here so GitHub picks up on it) closes #1659.

Unless @jougs points out otherwise, this is still the main documentation for how to write extension modules (there are no docs other than the readme on https://github.com/nest/nest-extension-module). As you rightfully point out though, these documents will eventually need some more finessing than I've done so far in this PR.

2021-04-14 15:45 UTC, jessica-mitchell requested changes
@clinssen looks good! I just have a few minor things that could be fixed up

2021-04-15 12:55 UTC, clinssen commented on doc/userdoc/contribute/neuron_models.rst
> +Handling Incoming Events
```suggestion
Handling incoming events
```

2021-04-15 12:57 UTC, clinssen commented
Cheers, all suggestions committed!

2021-04-15 16:43 UTC, jessica-mitchell approved these changes
LGTM

2021-04-15 16:47 UTC, jougs commented
@clinssen: many thanks for your work on this. May I ask you to check the boxes in #1659 that this PR covers?

If there's only the module documentation left, can you please remove it from the developer space and add it to https://github.com/nest/nest-extension-module by means of a PR? Either as a standalone file, or integrated into the README.md, whichever looks more suitable to you. I will then update the content in the context of #1717.

2021-04-16 06:27 UTC, heplesser commented
@jougs In light of you comments I made you reviewer no 2 :).

2021-04-19 15:27 UTC, clinssen commented
@jougs: this PR closes that issue and checks all the boxes, except for two (material) changes compared to the earlier suggestions:

* [`xcode_workflow.md`](https://github.com/nest/nest-simulator/blob/gh-pages/xcode_workflow.md)   -> removed
* [`tokens_and_datums.md`](https://github.com/nest/nest-simulator/blob/gh-pages/tokens_and_datums.md)   -> removed

Regarding the move to https://github.com/nest/nest-extension-module, this could be a good test of our intersphinx support. But that escalates the scope of the PR a bit, as I will have to set up the doc build environment and I think this is the first time we'll be deploying intersphinx. (@jessica-mitchell: please tell me if I'm wrong!) If you're OK with it, I'll create a seperate issue.

2021-04-20 08:10 UTC, jougs commented
@clinssen: See https://github.com/clinssen/nest-simulator/pull/5 for a PR that takes care of the Token documentation. I already checked off in #1659, anticipating you merge soon.

2021-04-20 08:32 UTC, jougs requested changes
Thanks!

I have marked the files that I'd like to see moved to the Extension Module repository, but am otherwise fine (happy even!) with the changes.

2021-04-20 08:32 UTC, jougs commented on CONTRIBUTING.md
> +The NEST simulator is a scientific tool and as such it is never ready and constantly changing to meet the needs of novel neuroscientific endeavors. Here you find the most important information on how
Unrelated, but still.

```suggestion
The NEST simulator is a scientific tool and as such it is never finished and constantly changing to meet the needs of novel neuroscientific endeavors. Here you find the most important information on how you can contribute to NEST. This document is an excerpt from our [Contributing to NEST documentation](https://nest-simulator.readthedocs.io/en/latest/contribute/index.html), which provides more detailed information.
```

2021-04-20 08:32 UTC, jougs commented on doc/userdoc/contribute/extension_modules.rst
> +   This rebuilds only the NEST executable.
This file should be moved to https://github.com/nest/nest-extension-module.

2021-04-20 08:32 UTC, jougs commented on doc/userdoc/contribute/neuron_models.rst
> +not local receivers.
This file should be moved to https://github.com/nest/nest-extension-module.

2021-04-20 08:32 UTC, jougs commented on doc/userdoc/contribute/synapse_models.rst
> +   register_connection_model< my_synapse >( "my_synapse" );
This file should be moved to https://github.com/nest/nest-extension-module.

2021-04-20 08:32 UTC, jougs commented on doc/userdoc/contribute/synapses_overview.rst
> +unordered in time.
This file should be moved to https://github.com/nest/nest-extension-module.

2021-04-20 08:32 UTC, jougs commented on doc/userdoc/contribute/index.rst
> +See :doc:`synapses_overview` and :doc:`synapse_models`.
```suggestion
Writing an extension module
---------------------------

See `https://github.com/nest/nest-extension-module`_.

Writing neuron and synapse models
---------------------------------

See `https://nestml.readthedocs.io/en/latest/`_.
```

2021-04-22 08:41 UTC, jougs reviewed
So do I see it right that the only file left now is the XCode workflow documentation?

2021-04-22 08:45 UTC, clinssen commented
Yes—left behind, that is... did we have an idea for still fitting this in somewhere?

2021-04-22 08:47 UTC, jougs commented
I think the proper place would be https://nest-simulator.readthedocs.io/en/latest/contribute/nest_with_ides.html

2021-04-22 09:01 UTC, clinssen commented
Done!

2021-04-22 12:07 UTC, jougs approved these changes
Many thanks for your work on this. I have no more requests for changes and approve wholeheartedly :-)

@jessica-mitchell: can you please quickly indicate if you're still happy even with the changes after your approval?

I assume the next logical step after merging this would be to delete the `gh-pages` branch from the repository?

2021-04-22 12:26 UTC, jessica-mitchell commented
Yep everything looks good from my end @jougs

2021-04-22 12:46 UTC, merged

2021-04-22 12:48 UTC, jougs commented
And branch deleted. Yay!