Propagate the `cython --version` error
nest/nest-simulator pull request #2001
Opened 2021-04-08 18:49 UTC by Helveg

Fixes #2000 by propagating the error that `cython --version` throws

2021-04-19 09:25 UTC, gtrensch approved these changes
Thanks for this contribution. It looks good to me :+1: .
Approving.

2021-04-19 12:00 UTC, Helveg commented
Will do, it will require some debugging as this could only occur if Cython returns an error code to `cython --version` or if it prints it output to `stderr`, both seem unlikely. 😕

2021-04-19 12:56 UTC, clinssen commented
``cython --version`` apparently prints to stderr, not stdout. D'oh!

2021-04-19 13:12 UTC, Helveg commented
O_O ok, will fix, the exit code is 0 though I hope?

2021-04-20 14:22 UTC, gtrensch commented on cmake/FindCython.cmake
> +      # printed to stderr instead.
```suggestion
      # In cython v0.29.3 the version string is written to stderr and not to stdout, as one would expect.
```

2021-04-20 14:24 UTC, gtrensch commented on cmake/FindCython.cmake
> +      # printed to stderr instead.
I've changed the comment to be more precise what the issue is.

2021-04-20 14:30 UTC, gtrensch requested changes
Thanks for the update! 
I ran some CMake tests forcing some errors to verify the robustness of the solution. It works! Problem is, as @clinssen already mentioned, that cython writes the version string to stderr and not stdout, as one could expect. This might perhaps change in future. I've suggested to adjusted the comment to be more precise what the issue is. Please check. I would then approve this PR.

2021-04-20 14:41 UTC, Helveg commented
Merged the suggestion

2021-04-20 17:40 UTC, gtrensch approved these changes
Approved!

2021-04-20 18:05 UTC, clinssen approved these changes

2021-04-21 05:21 UTC, merged