Link PyNEST functions in documentaton
nest/nest-simulator pull request #2010
Opened 2021-04-13 08:47 UTC by jessica-mitchell

This PR provides links to the API functions in the documentation, specifically restructuredtext files in doc/userdoc.
There are still files to update in the nest-3 guides, but waiting for #1929 to be merged, so this is still incomplete.

Note: the basic syntax for links to functions is :py:func:\`.FunctionName\` but `get()` and `set()` need a more specific syntax :py:func:\`~nest.lib.hl_api_types.NodeCollection.get\`
For future documentation, this syntax should be used to create links. (And is mentioned in styleguide #1986 )

Resolves #1878

2021-07-20 18:06 UTC, jougs commented
@steffengraber, @jasperalbers: could you please review? If you don't have time right now, please quickly indicate this, so we can try to find other reviewers. Thanks!

2021-07-21 15:14 UTC, jasperalbers reviewed
Works as intended, very useful! I left a few comments.

2021-07-21 15:14 UTC, jasperalbers commented on doc/userdoc/guides/connection_management.rst
>  indices can be specified under the key `params_map`. Alternatively,
```suggestion
to :py:func:`.Connect` under the key ``cg`` of the connection specification
dictionary and evaluated internally. If the Connection Generator
provides values for connection weights and delays, their respective
indices can be specified under the key ``params_map``. Alternatively,
```

Should these be double apostrophes as many other code-like objects or are the single ones intended here?

2021-07-21 15:14 UTC, jasperalbers commented on doc/userdoc/guides/connection_management.rst
> +specification argument to ``Connect1()``.
```suggestion
specification argument to ``Connect()``.
```
possible typo

2021-07-21 15:14 UTC, jasperalbers commented on doc/userdoc/guides/spatial/guide_spatially_structured_networks.rst
>  Free probabilistic connections using `pairwise_bernoulli`
```suggestion
Free probabilistic connections using ``pairwise_bernoulli``
```
Possible miss of using double quotes (ignore this if intended).

2021-07-22 08:47 UTC, jessica-mitchell commented on doc/userdoc/guides/connection_management.rst
> +as third argument to ``Connect()``, or by setting the key ``rule`` in
Yes, I was trying to only link each function once per paragraph or section.

2021-07-25 11:25 UTC, jessica-mitchell commented
Hi @jasperalbers I have addressed your comments, could you please take another look? thanks!

2021-07-27 05:54 UTC, steffengraber requested changes
Excellent! Really helpful! Found only one little thing.

2021-07-27 16:58 UTC, jessica-mitchell commented on doc/userdoc/guides/nest2_to_nest3/nest3_features/nest3_handling_connections.rst
> +then be applied to each source-target pair. To create these collocated synapses, :py:func:`.CollocatedSynapses` must be used
```suggestion
then be applied to each source-target pair. To create these collocated synapses, :py:class:`.CollocatedSynapses` must be used
```

2021-07-28 05:35 UTC, steffengraber approved these changes
:+1 from my side.

2021-08-02 11:29 UTC, jasperalbers approved these changes
Looks good to me!

2021-08-02 14:21 UTC, jougs commented
@jessica-mitchell: I'll merge as soon as you fix the conflicts ;-)

2021-08-16 09:59 UTC, jougs commented
@jessica-mitchell: can you maybe merge master again? If that does not solve the static code check problems, I can have a closer look.

2021-08-16 13:41 UTC, jougs commented
I'm merging even thought the one static check still fails. I'll fix that in master.

2021-08-16 13:41 UTC, merged