Add documentation on parameter comparators
nest/nest-simulator pull request #2040
Opened 2021-05-18 12:55 UTC by hakonsbm

Fixes #1588.

2021-05-28 12:02 UTC, stinebuu reviewed
Thanks, I have some questions, they might be really obvious, but I was confused :sun_with_face:

2021-05-31 08:58 UTC, hakonsbm commented
@stinebuu I've reworded the sentence. Does it make more sense now?

2021-06-02 11:05 UTC, stinebuu approved these changes

2021-06-02 17:50 UTC, jessica-mitchell requested changes
Looks good, just a few minor suggestions

2021-06-02 17:50 UTC, jessica-mitchell commented on doc/userdoc/guides/nest2_to_nest3/nest3_features/parametrization.rst
> +    nest.logic.conditional(nest.random.uniform(min=-1., max=1.) > 0., 0.5, 0.)
```suggestion
    nest.logic.conditional(nest.random.uniform(min=-1., max=1.) > 0.0, 0.5, 0.0)
```

I know you don't have to add a zero after the decimal, but I think it looks strange especially being followed by a comma

2021-06-02 17:50 UTC, jessica-mitchell commented on doc/userdoc/guides/nest2_to_nest3/nest3_features/parametrization.rst
> +but also without it if the desired result is zero where the comparison is false.
```suggestion
You can omit the ``nest.logic.conditional()`` if the desired result is zero when the comparison is false.
```

2021-06-02 17:50 UTC, jessica-mitchell commented on doc/userdoc/guides/nest2_to_nest3/nest3_features/parametrization.rst
> +respectively. The resulting comparison ``nest.Parameter`` can be used in a ``nest.logic.conditional()``,
```suggestion
respectively. The resulting comparison ``nest.Parameter`` can be used in a ``nest.logic.conditional()``.
```

2021-06-02 17:50 UTC, jessica-mitchell commented on doc/userdoc/guides/nest2_to_nest3/nest3_features/parametrization.rst
> +    0.5*(nest.random.uniform(min=-1., max=1.) > 0.)
```suggestion
    0.5*(nest.random.uniform(min=-1., max=1.) > 0.0)
```

2021-06-02 17:50 UTC, jessica-mitchell commented on doc/userdoc/guides/nest2_to_nest3/nest3_features/parametrization.rst
> +    # This comparison can be used directly without the nest.logic.conditional() function.
```suggestion
    # This comparison can be used without the nest.logic.conditional() function.
```

2021-06-03 11:11 UTC, jessica-mitchell approved these changes
Thanks @hakonsbm!

2021-06-03 13:21 UTC, merged