update_value func moved to dictutils.h
nest/nest-simulator pull request #2051
Opened 2021-05-26 21:27 UTC by ashvish183

Merge it or tell my where I am wrong

2021-05-27 05:38 UTC, heplesser requested changes
@ashvish183 Thank you for your contribution. Could you contact me by email (info@nest-initiative.org) about some formalities?

2021-05-27 05:38 UTC, heplesser commented on sli/dictutils.h
> +/* Polymorphic version of update_value.
Adjust this comment to the same (doxygen) style as the other function-describing comments in `dictutils.h`.

2021-07-01 09:00 UTC, stinebuu commented on sli/dictutils.h
> +bool
You need an `inline` before `bool` to make the code compile. This is why the Github actions fail. So, it needs to be `inline bool` here.

2021-08-09 12:59 UTC, heplesser commented
@ashvish183 Do you plan to work more on this PR? Otherwise, I will close it due to inactivity.

2021-09-07 08:15 UTC, jougs commented
Closing due to inactivity.

2021-09-07 08:15 UTC, closed without merging

2021-09-07 08:18 UTC, jougs commented
@stinebuu: please feel free to adopt the underlying branch and create a new PR from it. I think copyright is not an issue here, as this simply moves already existing code from one place to another.