Add timers for NEST 2.14.1
nest/nest-simulator pull request #2063
Opened 2021-06-09 13:15 UTC by jarsi

This PR adds timer functionality to NEST 2.14.1. The usage and functionality is similar to what is implemented in PR #1778 and addresses the issues raised in #1471.

These timers are implemented:
* `time_gather_spike_data`
* `time_simulate` (basic timer, always enabled)
    * nested in `time_simulate:`
        * `time_update`
        * `time_gather_spike_data`
            * nested in `time_gather_spike_data:`
                * `time_collocate_spike_data`
                * `time_communicate_spike_data`
                * `time_deliver_spike_data`

In contrast to PR #1778, these timers are not implemented due to the infrastructure change:
* `time_communicate_prepare` (basic timer, always enabled)
    * nested in `time_communicate_prepare:`
        * `time_gather_target_data`
            * nested in `time_gather_target_data:`
                * `time_communicate_target_data`

I am not too familiar with the construction phases. Furthermore the order of collocate, communicate and delivery is different and I am not sure how this influences the `time_gather_spike_data`. So besides the normal review process, I'd ask specifically for input for these parts:

* `time_construction_create` (basic timer, always enabled)
* `time_construction_connect` (basic timer, always enabled)
* `time_gather_spike_data`

2021-06-11 10:08 UTC, jarsi commented
Could one of you, @stinebuu or @hakonsbm, look at the use of `time_construction_create` and `time_construction_connect`? I could imagine these timers need some correction.

@jakobj, could you check whether `time_gather_spike_data` is implemented correctly?

2021-06-15 12:28 UTC, hakonsbm requested changes
The `time_construction_create` timer looks fine.

For `time_construction_connect` there should be timers in the `ConnectLayer` function in `topologymodule.cpp` to get connection-times for spatial connections. 

There should also be timers for `DataConnect`. Note that there are two high-level functions for `DataConnect` in `nestmodule.cpp`.

And see below for some other comments.

2021-06-15 12:28 UTC, hakonsbm commented on nestkernel/nest_names.cpp
>  const Name time_communicate( "time_communicate" );
Should these be removed too?

2021-06-15 12:28 UTC, hakonsbm commented on nestkernel/simulation_manager.cpp
> +  // reset_timers_for_dynamics();
```suggestion
```

2021-06-15 12:28 UTC, hakonsbm commented on nestkernel/connection_manager.h
> +  Stopwatch sw_construction_connect;
This should have a doxygen documentation comment, e.g. `Stopwatch measuring connection time`.

2021-06-15 12:28 UTC, hakonsbm commented on nestkernel/event_delivery_manager.h
> +  Stopwatch sw_communicate_spike_data_;
These should also have doxygen comments.

2021-06-15 12:28 UTC, hakonsbm commented on nestkernel/node_manager.h
> +  Stopwatch sw_construction_create_;
Add doxygen comment.

2021-06-16 10:12 UTC, jarsi commented
Thanks for the review @hakonsbm. I added and changed the functionality as you suggested. Could you have a look again?

2021-06-16 10:40 UTC, hakonsbm approved these changes
Thanks! Looks good to me now.

2021-06-17 12:32 UTC, jarsi commented
Thanks for you measurements. The difference in communication time is due to a now missing synchronization point. Previously this synchronization was not measured and excluded from the communication time. Now it's implicitly contained in the call to communicate.

![Screenshot from 2021-06-17 10-55-28](https://user-images.githubusercontent.com/34653647/122396744-9a7f6f00-cf78-11eb-9605-06de21439cfb.png)

2021-07-20 18:10 UTC, jougs approved these changes
LGTM!

@ackurth: could you please indicate if @jarsi's last reply settles your concerns? Thanks!

2021-07-21 11:03 UTC, ackurth approved these changes

2021-07-21 14:28 UTC, jougs commented
Many thanks to everyone!

@terhorstd: let me know when you're in the mood for a release :cat:

2021-07-21 14:28 UTC, merged