Add Arbor backend to GitHub Actions testing matrix
nest/nest-simulator pull request #2076
Opened 2021-06-14 08:16 UTC by hakonsbm

Also adds a test of the Arbor backend, based on the Arbor cosim example. Fixes #1556.

2021-08-16 09:35 UTC, lekshmideepu commented
I would take a look!

2021-09-02 10:53 UTC, gtrensch commented on pynest/nest/tests/arbor_backend_arbor_side.py
> +from mpi4py import MPI
```suggestion

from mpi4py import MPI
```

2021-09-02 10:54 UTC, gtrensch commented on pynest/nest/tests/arbor_backend_arbor_side.py
> +from mpi4py import MPI
Inserted a line break.

2021-09-02 12:04 UTC, gtrensch requested changes
That looks pretty good to me so far. 
Aside from the failed build due to mpi4py on macOS that needs to be investigated by a macOS expert, I made a few small suggestions to improve the comments. Could you check this please?

2021-09-03 08:52 UTC, heplesser requested changes
Looks good, just some small comments below. Could you merge master to switch test running to pytest? That should also solve the problem on macOs.

2021-09-03 08:52 UTC, heplesser commented on pynest/nest/tests/arbor_backend_arbor_side.py
> +# Based on arbor_proxy.py in arbor_cosim_example.
Change file name to `arbor_backend_test_arbor_side.py` and add a comment here that this file is run by `test_arbor_backend.py` together with `arbor_backend_test_nest_side.py`.

2021-09-03 08:52 UTC, heplesser commented on pynest/nest/tests/arbor_backend_nest_side.py
> +# It requires NESTIO + ARBOR-NESTIO.
Change file name to `arbor_backend_test_nest_side.py` and add a comment here that this file is run by `test_arbor_backend.py` together with `arbor_backend_test_arbor_side.py`.

2021-09-03 08:52 UTC, heplesser commented on pynest/nest/tests/test_arbor_backend.py
> +# along with NEST.  If not, see <http://www.gnu.org/licenses/>.
Add a comment here that this file requires `arbor_backend_test_arbor_side.py` and `arbor_backend_test_nest_side.py`.

2021-09-03 08:52 UTC, heplesser commented on pynest/nest/tests/test_arbor_backend.py
> +def suite():
Since we now run via PyTest (see #2127), everything below is no longer needed.

2021-09-03 10:09 UTC, heplesser approved these changes

2021-09-03 10:15 UTC, heplesser commented
@hakonsbm macOS still fails, even though mpi4py is definitely installed. I will take another look on the Mac.

2021-09-03 11:09 UTC, heplesser requested changes
I think the proper solution for now is to not test the Arbor backend on macOS; our test setup for macOS does not provide all necessary components. I suggested a change for that below.

Python-based tests have moved in master. Please move the Arbor tests from `pynest/nest/tests` to `testsuite/pytests`.

2021-09-03 11:09 UTC, heplesser commented on .github/workflows/nestbuildmatrix.yml
> +             os: macos-latest
Insert below here
```
   - xNEST_BUILD_TYPE: "ARBOR_BACKEND"
              cpp_compiler: "clang"
              os: macos-latest
```
to completely prevent Arbor testing on macOS. At present, we only perform a minimal test on macOS to limit resource use; not all necessary requirements for a full test are installed.

2021-09-03 11:38 UTC, heplesser approved these changes

2021-09-03 13:06 UTC, gtrensch approved these changes
👍 Approved.

2021-09-03 13:08 UTC, merged