Impement Hover Tooltip for Read the Docs
nest/nest-simulator pull request #2109
Opened 2021-07-14 07:35 UTC by mahdienan

This pr implements a sphinx extension to allow hovering functionality in the documentation on ReadtheDocs. The content of the text when hovering is retrieved from the glossary file which was also updated. The extension uses a sphinx role defined in _ext/HoverXTooltip.py. To make the extension match the style of NEST, we make use of CSS/JS defined in bootstrap.min.css, bootstrap.min.js, and hoverxtooltip.css. The name of the role is `:hxt_ref:`\`TERM\`. This role looks for descriptions of a term in the glossary.rst file and adds the first line of the definition as the content of the pop-up. The hovering function can be also used by explicitly defining the content of the pop-up by using `:hxt:`\`TERM <hxt:CONTENT>\`.

In the glossary file entries, the first line of the descriptions for the terms will be displayed as the content of the pop-up and then there must be an empty line to prevent the entire text of the description from being displayed in the pop-up.

As an example, the PyNEST tutorials have been implemented. An example build can be found [here](https://nest-simulator-doc.readthedocs.io/en/hoverxtooltip_plugin/tutorials/pynest_tutorial/part_1_neurons_and_simple_neural_networks.html).

2021-07-22 10:12 UTC, jessica-mitchell requested changes
Thanks @mahdienan for all your hard work on this! I have a few minor English language and mark up suggestions.
Also can you please sort the glossary alphabetically (I think it's the option :sorted: but double check that).

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   A property of a synapse which allows it to be modified for a period of time when some constraints are satisfied.
```suggestion
   A property of a synapse, which allows it to be modified for a period of time when some constraints are satisfied
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   The membrane potential at which a neuron causes no net current flow.
```suggestion
   The membrane potential in which a neuron causes no net current flow
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   Instance of synaptic response.
```suggestion
   Instance of a synaptic response
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   Mechanism of making a synapse stronger by increasing the weight. Opposite to depression.
```suggestion
   Mechanism of making a synapse stronger by increasing the weight
   
   Opposite to depression
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   Mechanism of making a synapse weaker by decreasing the weight. Opposite to facilitation.
```suggestion
   Mechanism of making a synapse weaker by decreasing the weight 
   
   Opposite to facilitation.
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   Synapse with spike-timing dependent plasticity.
```suggestion
   Synapse with spike-timing dependent plasticity
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   Synapse with a fixed weight.
```suggestion
   Synapse with a fixed weight
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   The time before a new action potential can take place.
```suggestion
   The time before a new action potential can take place
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   refer to spike-time statistical analysis
```suggestion
   spike-time statistical analysis
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   The part of the dentrite which is further away from the soma.
```suggestion
   The part of the dentrite that is furthest away from the soma
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   The part of the dentrite which is closer to the soma.
```suggestion
   The part of the dentrite which is closest to the soma
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   An interval after the neurons fires a spike in which it is prevent to fire a spike again.
```suggestion
   An interval after a neuron fires a spike to prevent it from firing  a spike again
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   Amount of connections to post-synaptic cells.
```suggestion
   Amount of connections to post-synaptic cells
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   Amount of connections from pre-synaptic cells.
```suggestion
   Amount of connections from pre-synaptic cells
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   The extent to which a pre-synaptic neuron affects a post-synaptic neuron.
```suggestion
   The extent to which a pre-synaptic neuron affects a post-synaptic neuron
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   A device that allows to record analog quantities (e.g. membrane voltage) of a neuron over time.
```suggestion
   A device to record analog quantities (e.g., membrane voltage) of a neuron over time
```

2021-07-22 10:12 UTC, jessica-mitchell commented on doc/userdoc/glossary.rst
> +   Spikes are encoded as events in nest.
```suggestion
   Spikes are encoded as events in NEST
```

2021-07-27 21:36 UTC, jougs commented
@mahdienan: could you please merge master and resolve the conflict? Thanks!

2021-09-05 18:30 UTC, jougs commented
@mahdienan: any progress on this? Thanks!

2021-09-15 20:06 UTC, jougs requested changes
Many thanks for your contribution!

I have added some inline comments and have two more general questions:
* Why are the three figures part of this PR? I'm fine if they have to be here, but would not want them in if they were added by accident.
* Shouldn't this (awesome!) new feature be applied to many more files (examples, documentation files)?

2021-09-15 20:06 UTC, jougs commented on doc/userdoc/glossary.rst
> +   Capacitance of the membrane in pF
```suggestion
   capacitance of the membrane in pF
```

2021-09-15 20:06 UTC, jougs commented on doc/userdoc/glossary.rst
> +   Capacitance of the membrane in pF
Also make all other items consistently lower or upper case. @jessica-mitchell?

2021-09-16 06:39 UTC, jessica-mitchell commented
>     * Shouldn't this (awesome!) new feature be applied to many more files (examples, documentation files)?
@jougs when we were discussing  this project, we decided that we wanted this PR to focus mainly on the tool, with a few examples to showcase its usage. A subsequent PR will come to add this to other documentation.

2021-09-16 15:39 UTC, jougs commented
@jessica-mitchell: fine by me. Looking forward to that PR :-)

Regarding the failing checks on GitHub Actions:
* I already noted the missing copyright header for `doc/userdoc/_ext/HoverXTooltip.py` in my comments above. 
* After some investigation, it seems that we can't actually silence warnings for the [failing lines in `pynest/examples/clopath_synapse_spike_pairing.py`](https://github.com/nest/nest-simulator/pull/2109/checks?check_run_id=3614462905#step:12:3738) due to the unwillingness of pycodestyle's developers (see https://github.com/PyCQA/pycodestyle/issues/924). Please ignore for now.
* I've just removed the whitespace from the empty line in `testsuite/pytests/test_regression_issue-2069.py` in master. Pulling should thus fix that (and at the same time shadow the problem above in the next run of the CI...)

2021-11-05 11:17 UTC, terhorstd commented
Fixed last conflict that came in due to merge of  #2165 . Can be merged as soon as test pass.

2021-11-05 11:53 UTC, jougs commented
Many thanks! Merging :-)

2021-11-05 11:53 UTC, merged