Clean up NEST Server
nest/nest-simulator pull request #2111
Opened 2021-07-15 17:51 UTC by jougs

This PR removes the serialization functionality from NEST Server, as this a) is not needed anymore since #2024 was merged and b) could lead to deadlocks in MPI-enabled scenarios. It also clarifies and extends several docstrings and cleans up the code structure a bit.

@babsey: can you please verify the changes in the context of NEST Desktop?
@jessica-mitchell: can you please have a look at the docstrings?

2021-07-15 20:50 UTC, babsey approved these changes
LGTM!. 

It works with NEST Desktop and requests from curl seems full operational without error.

I tested with these command lines.
```
# Get and set resolution in kernel
curl -s http://localhost:5000/api/GetKernelStatus | jq -r .resolution
curl --header "Content-Type: application/json" -d '[{"resolution": 1}]' http://localhost:5000/api/SetKernelStatus
curl --header "Content-Type: application/json" -d '"resolution"' http://localhost:5000/api/GetKernelStatus

# Set defaults without keywords
curl --header "Content-Type: application/json" -d '["iaf_psc_alpha", {"V_m": -60}]' http://localhost:5000/api/SetDefaults
curl -s --header "Content-Type: application/json" -d '"iaf_psc_alpha"' http://localhost:5000/api/GetDefaults | jq -r .V_m

# Set defaults with keywords
curl --header "Content-Type: application/json" -d '{"model":"iaf_psc_alpha", "params":{"V_m": -70}}' http://localhost:5000 api/SetDefaults
curl --header "Content-Type: application/json" -d '["iaf_psc_alpha", "V_m"]' http://localhost:5000/api/GetDefaults

# Create a node and get status
curl --header "Content-Type: application/json" -d '"iaf_psc_alpha"' http://localhost:5000/api/Create
curl -s --header "Content-Type: application/json" -d '[[1]]' http://localhost:5000/api/GetStatus | jq -r .[0].V_m

# Set status of node
curl --header "Content-Type: application/json" -d '[[1], {"V_m":-55}]' http://localhost:5000/api/SetStatus
curl --header "Content-Type: application/json" -d '[[1], "V_m"]' http://localhost:5000/api/GetStatus
```

2021-07-15 23:57 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    print(f"##\n## DATA COMBINATION ERROR: response={response}\n##\n", flush=True)
```suggestion
    log("combine_data", f"ERROR: cannot combine response={response}")
```

2021-07-15 23:57 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    produced it.
```suggestion
    of the result can vary depending on the call that produced it.
```

2021-07-16 11:20 UTC, jessica-mitchell requested changes
Looks good, just a couple of points that need clearing up, and maybe a comma or two :)

2021-07-16 11:20 UTC, jessica-mitchell commented on pynest/nest/server/hl_api_server.py
> +    call a PyNEST API function if call_name is the name of such one.
What is meant by such one?

2021-07-16 11:20 UTC, jessica-mitchell commented on pynest/nest/server/hl_api_server.py
> +    and kwargs to all worker processes and only then execute the call
```suggestion
    and kwargs to all worker processes. Only then will it execute the call
```

2021-07-16 11:20 UTC, jessica-mitchell commented on pynest/nest/server/hl_api_server.py
> +    worker responses are collected, combined and returned to the caller.
```suggestion
    worker responses are collected, combined, and returned to the caller.
```

2021-07-16 11:20 UTC, jessica-mitchell commented on pynest/nest/server/hl_api_server.py
> +    process (i.e. the task with rank 0) in a distributed scenario.
```suggestion
    process (i.e., the task with rank 0) in a distributed scenario.
```

2021-07-16 11:20 UTC, jessica-mitchell commented on pynest/nest/server/hl_api_server.py
> +    # the outside, so we don't.
"so we don't" what?

2021-07-16 11:20 UTC, jessica-mitchell commented on pynest/nest/server/hl_api_server.py
> +    If this function is run in a serial context, i.e., without MPI,
```suggestion
    If this function is run in a serial context, that is, without MPI,
```

2021-07-16 11:20 UTC, jessica-mitchell commented on pynest/nest/server/hl_api_server.py
> +    it returns the only response immediately.
What do you mean by only response?

2021-07-16 11:20 UTC, jessica-mitchell commented on pynest/nest/server/hl_api_server.py
> +    of the result can vary depending on the call of the call that
This seems confusing to me "call of the call", could you clarify, maybe with an example?

2021-07-16 11:20 UTC, jessica-mitchell commented on extras/nest-server-mpi
> +            # subset of processes throw, a deadlock due to mismatching
```suggestion
            # subset of processes throw an exception, a deadlock due to mismatching
```
Does that change make sense?

2021-07-16 14:06 UTC, jougs commented
@benef23, @christopherbignamini: this is the PR to watch.

2021-07-20 15:00 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    it returns the only response immediately.
Rephrased in 43a5e66d1.

2021-07-20 15:02 UTC, jougs commented on extras/nest-server-mpi
> +            # subset of processes throw, a deadlock due to mismatching
Rephrased in cf10a0963.

2021-07-20 15:10 UTC, jougs commented
@jessica-mitchell: I have now updated most docstrings and am pretty happy with them. What do you think?!

2021-07-20 16:45 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    kwargs as function arguments.
```suggestion
    of a PyNEST API function, it will call that function and pass args
    and kwargs to it.
```

2021-07-20 16:45 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    responses are collected, combined and returned to the caller.
```suggestion
    If the server is run with MPI, this function will first communicate
    the call type ("exec" or API call) and the args and kwargs to all
    worker processes. Only then will it execute the call in the same
    way as described above for the serial case. After the call, all
    worker responses are collected, combined and returned.
```

2021-07-20 16:45 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    print("\n========================================\n", flush=True)
```suggestion
    print(f"\n{'='*40}\n", flush=True)
```

2021-07-20 16:45 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    log("combine_data", f"ERROR: cannot combine response={response}")
```suggestion
    log("combine()", f"ERROR: cannot combine response={response}")
```

2021-07-20 16:45 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    # prevents Flask from performing such changes
```suggestion
    # prevents Flask from performing such changes.
```

2021-07-20 16:45 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    """Get the nest call and transform arguments.
```suggestion
    """Get the NEST API call and convert arguments if neccessary.
```

2021-07-20 16:45 UTC, jougs commented on pynest/nest/server/hl_api_server.py
> +    will do one of two things: if call_name is "exec", it will execute
```suggestion
    will do one of two things: If call_name is "exec", it will execute
```

2021-07-20 17:26 UTC, jessica-mitchell approved these changes
Thanks for the changes, looks good!

2021-07-20 18:01 UTC, jougs commented
Yay!

2021-07-20 18:02 UTC, merged