Pave the way for per-version transition guides
nest/nest-simulator pull request #2115
Opened 2021-07-28 16:56 UTC by jougs

This PR removes all transition information from anywhere but the transition guides. It also moves things around, so the transition guide can now be in a directory corresponding to the name of the Git tag under `release_notes`.

2021-07-29 11:26 UTC, jessica-mitchell commented
thanks for this PR @jougs 
I was wondering whether or not the NEST 3.0 features should be made more visible - simply because these are substantial new additions to NEST; a user who has 3.1 might need to reference the node or connection handling guides. I assume that the reference guide comparing NEST 2.x to 3.0 is also valid for 3.x. I don't think 3.0 release notes would necessarily be the first place a user would look for such information.

What do you think of moving these to the guides/ directory, remove the 3.0 specification but also link to them from the release notes section for NEST 3.0?

2021-07-29 16:05 UTC, jougs commented
I totally agree that the feature information from the NEST 3.0 transition guides needs to be integrated into the existing guides and probably new ones on node management and parametrization. Contrary to what I said in our video call earlier, that integration looks not so straightforward after all. I would thus postpone that to another PR and keep the scope of this one to what it currently is.

2021-07-29 17:30 UTC, jessica-mitchell requested changes
@jougs if you want to keep this PR simple, I'm fine with that for now

I just noticed some broken links - can you check, I think there are other places in userdoc/ that the file name and location have not been updated for spatially_structured_networks

2021-07-29 17:30 UTC, jessica-mitchell commented on doc/userdoc/release_notes/v3.0/index.rst
> +:doc:`spatially-structured networks <../../guides/spatial/index>`.
```suggestion
:doc:`spatially-structured networks <../../guides/spatially_structured_networks>`.
```

2021-07-29 17:30 UTC, jessica-mitchell commented on doc/userdoc/tutorials/pynest_tutorial/part_4_spatially_structured_networks.rst
> +   For comprehensive documentation of spatial properties and connectivity, see the :doc:`../../guides/spatial/guide_spatially_structured_networks`.
```suggestion
   For comprehensive documentation of spatial properties and connectivity, see the :doc:`../../guides/spatially_structured_networks`.
```

2021-07-29 17:30 UTC, jessica-mitchell commented on doc/userdoc/release_notes/v3.0/features/node_handles.rst
> +    If your nodes are spatially distributed (see :doc:`../../../guides/spatial/index`),
```suggestion
    If your nodes are spatially distributed (see :doc:`../../../guides/spatially_structured_networks`),
```

2021-07-30 05:43 UTC, jessica-mitchell approved these changes
thanks! lgtm

2021-07-30 14:03 UTC, jougs commented
@terhorstd: I will merge without waiting for your review, as this blocks some other work of mine. If you have additional ideas, please add a comment here.

2021-07-30 14:04 UTC, merged