Only call `set_connections_have_changed()` from thread 0
nest/nest-simulator pull request #2131
Opened 2021-08-24 09:22 UTC by stinebuu

Remove `set_connections_have_changed()` from `nest::ConnectionManager::disconnect` as  `set_connections_have_changed()` has already been called.

 `nest::ConnectionManager::disconnect()` is (by going backwards in the call-graph) called from two functions. The first is `SPManager::disconnect`, which already calls `set_connections_have_changed()` before going into the different threads:
https://github.com/nest/nest-simulator/blob/8c16625f39737318fceb97989e37fe6ab2b01342/nestkernel/sp_manager.cpp#L317-L319

The second is `SPmanager::update_structural_plasticity`, which calls `set_connections_have_changed()` if we either connect or disconnect, again from thread 0:
https://github.com/nest/nest-simulator/blob/8c16625f39737318fceb97989e37fe6ab2b01342/nestkernel/sp_manager.cpp#L413-L416

We therefore do not need to call `set_connections_have_changed()` in `nest::ConnectionManager::disconnect`.

This PR fixes #2125.

2021-08-25 07:12 UTC, heplesser reviewed
@stinebuu Thanks for the PR! It looks good in principle, but looking at the log of the FULL test case I do not see any output indicating that the regression test is actually run (it is installed). Could you check that?

2021-08-25 07:27 UTC, stinebuu commented
@heplesser I will have a look later today. It is run on my local computer, because it kept on failing, but I will check the output and see if I can figure out why it is not showing up in the tests here.

2021-08-25 09:32 UTC, heplesser commented
> @heplesser I will have a look later today. It is run on my local computer, because it kept on failing, but I will check the output and see if I can figure out why it is not showing up in the tests here.

Good that it failed on your machine, that should give some idea of where to search in the log ...

2021-08-25 12:13 UTC, stinebuu commented
@heplesser It looks like the problem is that we get a warning about the fact that the connections obtained by `GetConnections` is invalid after connecting the second time. I do not know why, but the warning prevents the test to be shown in the list of test. I have fixed it for this test now by setting the verbosity, but I suspect this is a general problem with the Python tests. There are for instance 2 other Python regression tests, and I cannot see them in the list, but when I make them fail they show up as failed in the end of the testsuite.

2021-08-25 12:22 UTC, hakonsbm commented
I think the problem is `grep --line-buffered "\.\.\. ok\|fail\|skip\|error"` in 

https://github.com/nest/nest-simulator/blob/8c16625f39737318fceb97989e37fe6ab2b01342/testsuite/do_tests.sh#L465

If there is any output between the three dots following the test name (written when starting the test) and the result (written when the test is finished), the test output for that test is not written to the log.

2021-08-31 08:45 UTC, stinebuu commented
As the problem with `do_tests.sh` is outside the scope of this PR, I suggest that be solved in another PR. I can create an issue for this.

2021-08-31 11:30 UTC, heplesser approved these changes

2021-08-31 14:59 UTC, hakonsbm requested changes
Looks quite nice, I have just a couple small suggestions.

2021-08-31 14:59 UTC, hakonsbm commented on testsuite/pytests/test_regression_issue-2125.py
> +import unittest
NumPy is unused.
```suggestion
import unittest
```

2021-08-31 14:59 UTC, hakonsbm commented on testsuite/pytests/test_regression_issue-2125.py
> +HAVE_OPENMP = nest.ll_api.sli_func("is_threaded")
Stick to either single or double quotes for strings throughout.

2021-08-31 14:59 UTC, hakonsbm commented on testsuite/pytests/test_regression_issue-2125.py
> +         # Make sure we are able to call Disconnect when we have number of threads more than one
```suggestion
        # Make sure we are able to call Disconnect when we have number of threads more than one
```

2021-09-01 07:57 UTC, hakonsbm requested changes

2021-09-01 07:57 UTC, hakonsbm commented on testsuite/pytests/test_regression_issue-2125.py
> +if __name__ == "__main__":
```suggestion
if __name__ == '__main__':
```

2021-09-01 09:10 UTC, hakonsbm approved these changes
Thanks!

2021-09-01 09:10 UTC, merged