Add warning about synaptic plasticity mechanisms and precise spike timing
nest/nest-simulator pull request #2137
Opened 2021-08-30 13:02 UTC by clinssen

Spin-off from #1840. For now, synaptic plasticity mechanisms will continue to ignore precise spike timing, because changing this is a larger project that raises further questions (to be addressed in #2035). To prevent confusion in the mean time, this PR adds warnings about this behaviour to all synaptic plasticity models that are affected.

2021-08-30 18:29 UTC, jessica-mitchell requested changes
@clinssen looks good; Aside from a minor comment about wording,  I noticed that the equations don't seem to render properly. The only thing looking a bit off is the lack of \\ at the end of the first line. Not sure if that will solve it.

2021-08-31 07:05 UTC, clinssen commented
- Fixed formatting of equations
- Wrapped long lines
- Merged suggestions for rewording in "jonke" synapses

2021-08-31 11:49 UTC, jessica-mitchell reviewed
Great, looks good, thanks!

2021-08-31 11:49 UTC, jessica-mitchell approved these changes

2021-09-03 22:11 UTC, heplesser approved these changes

2021-09-03 22:12 UTC, merged