Fix access of first element of an empty vector in pynestkernel
nest/nest-simulator pull request #2162
Opened 2021-09-13 12:56 UTC by niltonlk

This PR fix out of bound access in pynestkernel, reported in #2101.
With this fix, the two pynest examples (recording_demo.py and balancedneuron.py) reported in #2101 now succeed.

2021-09-13 15:41 UTC, jougs approved these changes
LGTM. I suggest a quick merge as this solves a real problem.

2021-09-14 06:49 UTC, hakonsbm requested changes
Just a tiny typo.

2021-09-14 06:49 UTC, hakonsbm commented on pynest/pynestkernel.pyx
> +    # skip when vector_ptr points to an ampty vector
```suggestion
    # skip when vector_ptr points to an empty vector
```

2021-09-14 09:17 UTC, heplesser commented
@niltonlk The failure is curious and likely related to using multiple test runners (if several tests write to files of the same name, we will get into trouble). Could you for now change `--numprocesses=auto` to `--numprocesses=1` in these two places:

https://github.com/nest/nest-simulator/blob/12a897ae685082da099d9f1d5c0a7a24efca9691/testsuite/do_tests.sh#L102

https://github.com/nest/nest-simulator/blob/12a897ae685082da099d9f1d5c0a7a24efca9691/testsuite/do_tests.sh#L473

2021-09-14 11:50 UTC, heplesser commented
I had another look at the code and am certain that nothing went wrong in the past, because for an empty `vector_ptr`
```c++
memcpy(array_data, &vector_ptr.front(), vector_ptr.size() * sizeof(vector_value_t));
```
would not have copied anything. But it is clearly incorrect to request `front()` of an empty container, to this fix is needed.

2021-09-14 14:38 UTC, hakonsbm approved these changes
Thanks! Looks good now.

2021-09-14 14:38 UTC, merged