Fix Clang warnings
nest/nest-simulator pull request #2201
Opened 2021-11-03 23:14 UTC by heplesser

This PR fixes a large number of warnings emitted by Apple Clang. Almost all of these warnings were due to explicit template class instantiations for Datum types, which could be removed by moving minimal methods from `_impl.h` files to `.h` files. This allowed removal of several `_impl.h` and `.cc` files.

2021-11-05 09:46 UTC, jougs approved these changes
Thanks for this cleanup. I did not follow each move individually, but trust the fact that the CI is happy.

2021-11-05 13:36 UTC, hakonsbm requested changes
Looks good. I just have one very minor formatting suggestion.

2021-11-05 13:36 UTC, hakonsbm commented on nestkernel/parameter.cpp
I think a single blank line here is sufficient.
```suggestion
```

2021-11-08 07:43 UTC, hakonsbm approved these changes
Thanks!

2021-11-08 07:43 UTC, merged