Add text to Izhikevich model doc
nest/nest-simulator pull request #2216
Opened 2021-11-22 20:59 UTC by jessica-mitchell

This PR adds some text to the model doc mentioning differences between NEST and the original author's model. Includes reference to Pauli et al. paper. 2018.

Not sure if this needs a lot more detail in the documentation or if link suffices.

2021-11-29 11:02 UTC, clinssen reviewed
Would move to reject (sorry!)

The paragraph about the numerics is redundant with the preceding paragraph, that already covers these issues, and how these are addressed in the NEST model. The comment about STDP does not seem relevant to this model as it is a neuron model without any direct relationship to synaptic plasticity.

2021-12-01 10:02 UTC, jougs requested changes
I tend to agree with @clinssen, but still think a reference to *Pauli et al.* would be a good addition to the model documentation.

2021-12-01 10:02 UTC, jougs commented on models/izhikevich.h
> +
```suggestion
For a detailed analysis and discussion of the numerical issues in the original publication, see [2]_.
```

2021-12-06 09:46 UTC, jougs approved these changes
Thanks!

2021-12-06 09:47 UTC, merged