Userdocs
nest/nest-simulator pull request #2246
Opened 2021-12-14 10:11 UTC by jougs

This PR addresses the remaining open action items and thereby fixes #1620.

2022-01-10 23:52 UTC, jougs commented
@terhorstd, @jessica-mitchell: friendly ping!

2022-01-13 15:52 UTC, jessica-mitchell requested changes
@jougs looks good, I just made some suggestions to mainly adding double back ticks in a few places

2022-01-13 15:52 UTC, jessica-mitchell commented on models/amat2_psc_exp.h
> +corresponding parameter values for mat2_psc_exp. If identical
```suggestion
corresponding parameter values for ``mat2_psc_exp``. If identical
```

2022-01-13 15:52 UTC, jessica-mitchell commented on models/cont_delay_synapse.h
> +1. set the delay as model default using SetDefaults, which is very
```suggestion
1. set the delay as model default using ``SetDefaults``, which is very
```

2022-01-13 15:52 UTC, jessica-mitchell commented on models/iaf_psc_alpha_canon.h
> +time and offset). If this node is connected to a spike_recorder, the
```suggestion
time and offset). If this node is connected to a ``spike_recorder``, the
```

2022-01-13 15:52 UTC, jessica-mitchell commented on models/iaf_psc_alpha_canon.h
> +property "precise_times" of the spike_recorder has to be set to true in
```suggestion
property "precise_times" of the ``spike_recorder`` has to be set to true in
```

2022-01-13 15:52 UTC, jessica-mitchell commented on models/iaf_psc_alpha_canon.h
> +The iaf_psc_delta_ps neuron accepts connections transmitting
```suggestion
The ``iaf_psc_delta_ps`` neuron accepts connections transmitting
```

2022-01-13 15:52 UTC, jessica-mitchell commented on models/iaf_psc_alpha_canon.h
> +CurrentEvents. These events transmit stepwise-constant currents which
```suggestion
``CurrentEvents``. These events transmit stepwise-constant currents which
```

2022-01-13 15:52 UTC, jessica-mitchell commented on models/iaf_psc_delta_ps.h
> +The iaf_psc_delta_ps neuron accepts connections transmitting
```suggestion
The ``af_psc_delta_ps`` neuron accepts connections transmitting
```

2022-01-13 15:52 UTC, jessica-mitchell commented on models/iaf_psc_delta_ps.h
> +CurrentEvents. These events transmit stepwise-constant currents which
```suggestion
``CurrentEvents``. These events transmit stepwise-constant currents which
```

2022-01-13 15:59 UTC, jougs commented on models/sinusoidal_poisson_generator.h
> +     \cdot \pi/180 )) >= 0
I think the variable names should definitely be `mathrm`. Good catch. Let's see who gets to deal with the conflict resolution fallout ;-)

2022-01-13 16:05 UTC, jougs commented
@jessica-mitchell: I have applied most of your suggestions and have two questions for the as-of-yet unapplied ones (mostly regarding `SetDefaults`):
* Instead of just making them typewriter by double-backticking them, what about marking the functions with `:py:func:`, so they are auto-linked to the PyNEST API?
* Is there a similar mechanism (existing/planned) for the models? The links into the model directory are also pretty much generic after all.

2022-01-13 17:43 UTC, jessica-mitchell commented
>     * Instead of just making them typewriter by double-backticking them, what about marking the functions with `:py:func:`, so they are auto-linked to the PyNEST API?

Ah yes, that would make more sense, I just wasn't thinking about it 

>     * Is there a similar mechanism (existing/planned) for the models? The links into the model directory are also pretty much generic after all.

Yes there is a way to do this but not implemented in any way yet;i think this could be something we look at in a future PR though

2022-01-13 22:41 UTC, jougs commented on models/stdp_dopamine_synapse.h
> +The common properties can only be set by SetDefaults and apply to all
Fixed in af4a0a15b.

2022-01-13 22:41 UTC, jougs commented on models/stdp_synapse_facetshw_hom.h
> +Common properties can only be set on the synapse model using SetDefaults.
Fixed in af4a0a15b.

2022-01-13 22:41 UTC, jougs commented on models/tsodyks_synapse_hom.h
> +   SetDefaults on the synapse model.
Fixed in af4a0a15b.

2022-01-13 22:41 UTC, jougs commented on models/cont_delay_synapse.h
> +1. set the delay as model default using SetDefaults, which is very
Fixed in af4a0a15b.

2022-01-14 11:45 UTC, merged