Clean up OpenMP pragmas
nest/nest-simulator pull request #2273
Opened 2022-01-20 14:06 UTC by jougs

This PR removes empty loops in case of single threading and generally cleans up and comments the OpenMP pragmas.

As the code in this PR is based on #2272 (by accident), this should only be merged after that.

2022-01-20 15:43 UTC, heplesser approved these changes
Thanks for cleaning up!

2022-01-21 08:02 UTC, hakonsbm requested changes
Thanks! I have just a tiny suggestion.

2022-01-21 08:02 UTC, hakonsbm commented on testsuite/pytests/test_events.py
> +        self.assertTrue(len(d['times']) > 0)
```suggestion
        self.assertGreater(len(d['times']), 0)
```

2022-01-21 09:37 UTC, hakonsbm approved these changes

2022-01-21 09:37 UTC, merged