Clean up an dadd links for compartmental model docs
nest/nest-simulator pull request #2313
Opened 2022-02-25 09:06 UTC by jessica-mitchell

This PR fixes a few formatting issues with the model documentation and adds a link on Read the Docs for the PyNEST examples.

2022-02-28 11:12 UTC, clinssen requested changes

2022-02-28 11:12 UTC, clinssen commented on models/cm_default.h
> +  In the ``nest.SetStatus()`` call, the ``receptor_type`` entry is string
```suggestion
  In the ``nest.SetStatus()`` call, the ``receptor_type`` entry is a string
```

2022-02-28 11:12 UTC, clinssen commented on models/cm_default.h
> +  ``receptor_type`` entry is and integer that specifies the receptor index.
```suggestion
  ``receptor_type`` entry is an integer that specifies the receptor index.
```

2022-02-28 11:12 UTC, clinssen commented on models/cm_default.h
> +variables, use the receptor index ``{state_variable_name}{receptor_index}`:`
```suggestion
variables, use the receptor index ``{state_variable_name}{receptor_index}``:
```

2022-03-04 11:27 UTC, jougs reviewed
Looks mostly good to me.

2022-03-04 11:27 UTC, jougs commented on models/cm_default.h
> +  is provided, multiple compartments receptors are added with a single
```suggestion
  is provided, multiple compartments' receptors are added with a single
```

2022-03-04 11:27 UTC, jougs commented on models/cm_default.h
> +``v_comp{compartment_index}``. Ion channels state variables can be recorded as well,
```suggestion
``v_comp{compartment_index}``. State variables for ion channels can be recorded as well,
```

2022-03-04 11:27 UTC, jougs commented on models/cm_default.h
> +The following parameters can be set using the ``AddCompartment`` function
There is no ``AddCompartment`` function anymore. This is now done via the call to ``SetStatus()``.
```suggestion
The following parameters can be used when adding compartments using ``SetStatus()``
```

2022-03-04 11:55 UTC, jougs approved these changes
LGTM!

2022-03-07 10:17 UTC, clinssen approved these changes

2022-03-07 10:17 UTC, merged