Return empty dictionary if `get()` is called on empty SynapseCollection
nest/nest-simulator pull request #2332
Opened 2022-03-08 13:41 UTC by stinebuu

This fixes #2318.

2022-03-08 14:39 UTC, hakonsbm requested changes
Could you also add a test of `conns.get()` on an empty SynapseCollection with specified keys (the case that should return `()`)?

2022-03-08 14:39 UTC, hakonsbm commented on pynest/nest/lib/hl_api_types.py
>              return ()
It's cleaner to not check `self.__len__() == 0 or num_conns == 0` twice.
```suggestion
        if self.__len__() == 0 or num_conns == 0:
            # Return empty tuple if get is called with an argument
            return {} if keys is None else ()
```

2022-03-16 12:23 UTC, med-ayssar approved these changes
Otherwise, it looks good to me.

2022-03-16 12:23 UTC, med-ayssar commented on testsuite/pytests/test_synapsecollection.py
>          conns.set(weight=10.)
Is not resetting the `kernel` equivalent to adding or deleting `connections`, and in that case we should get a warning from the `ConnectionManager` stating a similar `info` as the following: `ConnectionManager [Warning]: 
    New connections created, connection descriptors previously obtained using 
    'GetConnections' are now invalid`. In that case, the user should know that setting the `weight` in `conn` object won't be a valid operation, or maybe throw an error that  the `weight` isn't in the connection dictionary anymore.

2022-03-18 11:53 UTC, merged