Get sliprefix relative to the dynamic library
nest/nest-simulator pull request #2338
Opened 2022-03-10 23:29 UTC by isuruf

Fixes https://github.com/nest/nest-simulator/issues/2237

cc @steffengraber

2022-03-11 07:53 UTC, steffengraber commented
@jougs and @terhorstd Could you take a look at this, please? This could solve the problems with the conda packages.

2022-03-11 08:32 UTC, jougs commented
@isuruf: can you please look into the [failing static tests](https://github.com/nest/nest-simulator/runs/5507893387?check_suite_focus=true#step:9:313)? It is usually sufficient to install `clang-format` version 9 and run `build_support/format_all_c_c++_files.sh` in the repository to get the C++ formatting right.

2022-03-11 09:32 UTC, heplesser requested changes
Please see my detailed comments.

2022-03-11 09:32 UTC, heplesser commented on sli/slistartup.cc
> +#if defined(__linux__) || defined(__APPLE)
```suggestion
#if defined(__linux__) || defined(__APPLE__)
```

2022-03-11 09:32 UTC, heplesser commented on sli/slistartup.cc
> +        std::string result = std::string(soname);
```suggestion
       std::string result( info.dli_fname );
```
Can you find a more informative name than `result`?

2022-03-11 09:32 UTC, heplesser commented on sli/slistartup.cc
> +static std::string getsliprefix() {
Please add a doxygen comment explaining what this function does.

2022-03-11 09:33 UTC, jougs commented
@heplesser: can you please come to the hackathon? we're jointly working on this right now!

2022-03-18 11:09 UTC, jougs commented
Closing in favor of more generic fix in #2348. Anyway, thanks for your contribution!

2022-03-18 11:09 UTC, closed without merging