Deprecate spike_dilutor and prohibit its use with multiple threads
nest/nest-simulator pull request #2375
Opened 2022-04-21 08:58 UTC by heplesser

`spike_dilutor` is a variant of a parrot neuron which probabilistically forwards spikes. Each target neuron receives a different thinned spike train. Therefore, `spike_dilutor` needs to send `DSSpikeEvent`s and is implemented as a `StimulationDevice`. This conflicts, though, with the fact that the node also needs to receive spikes, leading to incorrect behavior when used with multiple threads (#2052).

At the same time, `bernoulli_synapse` implements exactly the same functionality in a proper, i.e., synapse, not pseudo-neuron, based way. This PR therefore

1. deprecates `spike_dilutor`
2. prohibits use of `spike_dilutor` with multiple threads
3. points to `bernoulli_synapse` as alternative.

This fixes #2052.

2022-04-21 09:27 UTC, hakonsbm requested changes
Looks good to me, except for a minor clarification in the test documentation.

2022-04-21 09:27 UTC, hakonsbm commented on testsuite/regressiontests/issue-2052.sli
> +Ensure that spike_dilutor cannot be created with a single but not multiple threads.
```suggestion
Ensure that spike_dilutor can be created with a single thread, but not with multiple threads.
```

2022-04-25 09:58 UTC, hakonsbm approved these changes
Thanks!

2022-05-17 22:46 UTC, jougs approved these changes
Thanks!

2022-05-17 22:47 UTC, jougs commented
@heplesser: can you please fix the conflicts? Thanks!

2022-08-02 06:04 UTC, merged