Prohibit multimeter-recording from noise_generator in multithreaded mode
nest/nest-simulator pull request #2377
Opened 2022-04-22 13:44 UTC by heplesser

As described in #2282, recording the average current produced by the `noise_generator` correctly when running on multiple threads would challenging to implement. Since I consider this a corner case anyways, I do not believe the effort would be worth it, as it would considerably complicate our code. Therefore, this PR explicitly prevents connections from `multimeter` to `noise_generator` if NEST runs with multiple threads.

The problem does not affect other generators (ac, dc, step_current, step_rate, sinusoidal_{gamma,poisson}) because they send deterministic values to the recorder which are identical for all threads so that it does not matter from which thread one records.

2022-04-25 07:20 UTC, hakonsbm requested changes
Just a small suggestion for a clarification in the documentation.

2022-04-25 07:20 UTC, hakonsbm commented on testsuite/regressiontests/issue-2282.sli
> +Name: testsuite::issue-2282 Ensure multimeter-recording from noise_generator prohibited in if multithreaded
```suggestion
Name: testsuite::issue-2282 Ensure multimeter-recording from noise_generator is prohibited if multithreaded
```

2022-04-25 07:46 UTC, hakonsbm approved these changes
Thanks!

2022-05-17 22:42 UTC, jougs requested changes
I would actually also want to see a hint about this restriction as a [RST `.. note::` admonition](https://docutils.sourceforge.io/docs/ref/rst/directives.html#toc-entry-1) around [line 131 of `noise_generator.h](https://github.com/nest/nest-simulator/pull/2377/files#diff-4342293d07738fb595c94ee7d3e0fbd1d7782a8c1e279c73d2da4bf3805b2225R131).

I also suggest to convert the test to Python, so you could actually check if the right exception is thrown.

2022-08-16 12:36 UTC, heplesser commented
@jougs I have now revised the documentation for the noise generator. Could you take a look? I do not quite see the point of converting to a Python-based test. I would allow me to test that exception `nest.lib.hl_api_exceptions.NESTErrors.Recording from a noise_generator is only possible in single-threaded mode.` is thrown, but extracting the interesting last part from it would be a bit of an effort and any change in the wording of the error message would break the test—or am I overlooking something here?

@jessica-mitchell Could you take a look at the revised documentation?

2022-10-07 09:24 UTC, jougs approved these changes
Just a single small suggestion.

2022-10-07 09:24 UTC, jougs commented on models/noise_generator.h
> +   noise generator. In multi-threaded mode, recording is noise current is prohibited for technical reasons.
```suggestion
   noise generator. In multi-threaded mode, recording of noise currents is prohibited for technical reasons.
```

2022-10-07 09:55 UTC, heplesser commented
> Just a single small suggestion.

Done :)

2022-10-07 10:59 UTC, heplesser commented
@jougs Could you resolve the one open conversation so that we can merge this one?

2022-10-07 13:03 UTC, merged