Update clang-format requirement and code to version 13
nest/nest-simulator pull request #2407
Opened 2022-06-01 21:51 UTC by jougs

This should fix  #2344.

2022-06-01 22:52 UTC, terhorstd approved these changes
LGTM :+1:
Thanks!

2022-06-02 10:01 UTC, heplesser requested changes
@jougs Thank you for the PR! I find some details around the versioning a bit confusing, please see my comments and suggestions.

2022-06-02 10:01 UTC, heplesser commented on doc/htmldoc/developer_space/guidelines/coding_guidelines_check.rst
> +We use clang-format version 13 in our CI.
```suggestion
We use clang-format version 13 in our CI. If your `clang-format` executable is not version 13, you need to specify an executable with version 13 explicitly with the `--clang-format` option to ensure consistency with the NEST CI.
```

2022-06-03 10:20 UTC, jougs commented on doc/htmldoc/developer_space/guidelines/coding_guidelines_check.rst
> +                                        Default: --clang-format=clang-format-13
Fixed in a632cdd14.

2022-06-03 10:20 UTC, jougs commented on build_support/check_code_style.sh
> +                                     Note: CLANG-FORMAT version 13 is required.
Right. Fixed in a632cdd14.

2022-06-03 10:20 UTC, jougs commented on environment.yml
> +    - clang-format == 13.0.0
Fixed in 186311122.

2022-06-03 11:54 UTC, heplesser approved these changes

2022-06-03 11:54 UTC, merged

2022-06-08 18:35 UTC, terhorstd commented on doc/htmldoc/developer_space/guidelines/coding_guidelines_check.rst
> +                                        Default: --clang-format=clang-format-13
actually the default is just `clang-format`, as the pip-installed one does not have the slot identifier (see `build_support/check_code_style.sh` line 33)