Fix spatial attribute positions of sliced NodeCollection
nest/nest-simulator pull request #2415
Opened 2022-06-21 07:37 UTC by hakonsbm

For internal consistency and efficiency, metadata of nodes in a sliced NodeCollection points to the metadata of the original NodeCollection. When getting the positions in the spatial parameter of a sliced NodeCollection, using `nodes.spatial['positions']`, positions for all nodes in the original NodeCollection is therefore returned. This PR adds a filter on the returned positions to only get positions of nodes in the sliced NodeCollection, which fixes #2414.

2022-08-18 14:24 UTC, mlober requested changes
The test only creates a single neuron when it should probably create multiple neurons and then create a sliced NC from that.

2022-08-18 14:32 UTC, nicolossus requested changes

2022-08-19 08:38 UTC, hakonsbm commented
@mlober @nicolossus Thanks for your reviews. I've updated with the suggested changes. Please have another look.

2022-08-19 09:02 UTC, nicolossus approved these changes
Thanks for the changes!

2022-08-23 16:49 UTC, mlober requested changes
Thanks for the changes. I still think the node collection object should be sliced first for the test, since now the NC is a standard one with size 10. 
I think it would work if you added the line 
nodes = nodes[::2] in the code. 
If I am misunderstanding, please explain.

2022-08-29 07:46 UTC, hakonsbm commented
@mlober The test already checks positions of a NC sliced to a single node. The positions of each node are gathered to a list that can be compared to the original positions:
https://github.com/nest/nest-simulator/blob/c99d3c5a8d327b36ec288be5844879cefa4110f2/testsuite/pytests/test_spatial/test_basics.py#L429

However, I've added a check of positions sliced with `nodes[::2]` as well now.

2022-08-31 10:29 UTC, mlober approved these changes
I see, thanks!

2022-08-31 10:31 UTC, merged