Adjust documentation to the actual behaviour of -Dwith-optimize
nest/nest-simulator pull request #2432
Opened 2022-07-21 12:23 UTC by steffengraber

Fix issue #2340

2022-07-21 12:24 UTC, steffengraber commented
@jarsi maybe you can have a look

2022-07-25 15:05 UTC, jarsi commented
Hi @steffengraber, thanks for starting this!

If I understand the cmake line correctly then the default is still ON although it states that it is OFF. Also the default optimization level is still set to O2 (see [here](https://github.com/nest/nest-simulator/blob/dd5b6134259885fc8a7dbbafd53020a3a9d96cef/cmake/ProcessOptions.cmake#L23-L33)).

I think it's a matter of preference whether with-opimize defaults to O2 or O3. We ran some tests a while ago and did not see huge differences between these two.

If I remember correctly, this  has not been finally resolved, maybe @heplesser and @diesmann could comment on this or we discuss this in one of our upcoming meetings.

2022-08-12 07:09 UTC, heplesser requested changes
@steffengraber Thanks for the PR. Please see my suggestions below to bring doc in step with behavior.

2022-08-12 07:09 UTC, heplesser commented on CMakeLists.txt
> +set( with-optimize ON CACHE STRING "Enable user defined optimizations [default=OFF (uses '-O0')]. When ON, '-O3' is used. Separate multiple flags by ';'." )
```suggestion
set( with-optimize ON CACHE STRING "Enable user defined optimizations [default=ON (uses '-O2')]. When OFF, no '-O' flag is passed to the compiler. Explicit compiler flags can be given; separate multiple flags by ';'." )
```

The code in `ProcessOptions.cmake` 

https://github.com/nest/nest-simulator/blob/d2500ca3ee16930c0b372694ec90bfe22cb3461f/cmake/ProcessOptions.cmake#L24

indicates that `-Dwith-optimize=ON` will use `-O2`, while `...=OFF` will add no O-option at all. If `-Dwith-optimize` is not given at all, `-O2` is also added. I confirmed these behaviors with a test. What the compiler does when used without any -O flag is up to the compiler and e.g., the Clang man page does not provide information about this.

2022-08-12 07:09 UTC, heplesser commented on doc/htmldoc/installation/cmake_options.rst
> +|                                                      | [default=OFF (uses '-O0')]. When ON, '-O3' is used. Separate     |
Adjust as above. I struggle adding that as a proper suggestion here since the text is split over modified and unmodified lines.

2022-08-18 10:28 UTC, heplesser approved these changes

2022-08-18 13:27 UTC, hakonsbm requested changes
Looks mostly good, but there is a missing square bracket in the rst-file (I hope my suggestion doesn't mess up the formatting).

2022-08-19 08:40 UTC, hakonsbm approved these changes
Thanks!

2022-08-19 08:40 UTC, merged