Only set relevant runpaths in libraries and executables
nest/nest-simulator pull request #2439
Opened 2022-07-27 16:11 UTC by StefanBruens

Libraries and executables install into different directories, and thus the relative directories to the library dir differ.

Only set the RUNPATH which actually applies, avoiding extraneous and invalid entries.

2022-08-01 14:54 UTC, terhorstd requested changes
Thanks @StefanBruens for the help on MacOS! This looks like a very useful distinction even beyond MacOS itself, and I was wondering if it would be possible to separate `$ORIGIN` into two different variables. With that we maybe could eliminate all `if` blocks and remain with a single block only, like
```
if ( APPLE )
   ORIGIN_LIB = @loader_path
   ORIGIN_EXE = @executable_path
else()
   ORIGIN_LIB = $ORIGIN
   ORIGIN_EXE = $ORIGIN
endif()
```

2022-08-15 14:50 UTC, heplesser requested changes
This is just a formal request for changes. Please send us a signed contributor agreement (https://nest-simulator.readthedocs.io/en/latest/_downloads/9b65adbdacba6bfed66e68c62af4e308/NEST_Contributor_Agreement.pdf) to info@nest-initiative.org.

2022-08-16 15:51 UTC, gtrensch requested changes

2022-08-16 15:51 UTC, gtrensch commented on models/CMakeLists.txt
> +if ( NOT APPLE )
Avoiding the negation here would result in better readability.

2022-08-16 15:51 UTC, gtrensch commented on nestkernel/CMakeLists.txt
> +if ( NOT APPLE )
Avoiding the negation here would result in better readability.

2022-08-16 15:51 UTC, gtrensch commented on pynest/CMakeLists.txt
> +  if ( NOT APPLE )
Avoiding the negation here would result in better readability.

2022-08-16 15:51 UTC, gtrensch commented on testsuite/cpptests/CMakeLists.txt
> +  if ( NOT APPLE )
Avoiding the negation here would result in better readability.

2023-06-21 21:02 UTC, jougs commented
@StefanBruens: Do you have any intentions on finishing this? Many thanks!

2024-03-22 08:26 UTC, lekshmideepu commented
No response from the user. Closing the PR

2024-03-22 08:26 UTC, closed without merging