Possibility to use `Parameter` object for indegree and outdegree
nest/nest-simulator pull request #2501
Opened 2022-10-13 13:13 UTC by hakonsbm

Attempts to fix #1615 by implementing the possibility to pass a `Parameter` object as indegree in `fixed_indegree` or as outdegree in `fixed_outdegree`. 

Example:
```python
conn_spec = {'rule': 'fixed_indegree', 
             'indegree': nest.random.normal(mean=20.0, std=2.0),
             'p': nest.spatial_distributions.gaussian(nest.spatial.distance, std=0.5),
             'allow_multapses': True}
```

2022-10-28 10:13 UTC, nicolossus requested changes
Looks good! I think that one now can pass a `Parameter` object as indegree/outdegree should be documented. I guess [doc/htmldoc/synapses/connection_management.rst](https://github.com/nest/nest-simulator/blob/master/doc/htmldoc/synapses/connection_management.rst) would be a good place for the documentation, but there might be another more suitable location.

2022-10-28 12:00 UTC, nicolossus reviewed
Thanks! I only have a minor grammatical suggestion, otherwise I approve once all tests pass

2022-10-28 12:15 UTC, nicolossus approved these changes

2022-10-31 10:37 UTC, jhnnsnk approved these changes
Looks good to me! Thank you very much for this useful addition! :+1:

2022-10-31 11:04 UTC, merged