Replace std::Vector with std::Set in
nest/nest-simulator pull request #2507
Opened 2022-10-19 14:32 UTC by med-ayssar

2022-10-19 15:11 UTC, med-ayssar commented
@jougs, could you take a look.

2022-10-19 16:53 UTC, jougs requested changes
Good in principle, but I would go a bit further. See my comments.

2022-10-19 16:53 UTC, jougs commented on nestkernel/secondary_event.h
> +#include <set>
For consistency with other files
```suggestion
// C++ includes:
#include <set>
```

2022-10-19 16:53 UTC, jougs commented on nestkernel/secondary_event.h
> +  virtual bool has_synid( const synindex synid ) const = 0;
It seems that this function is not used anywhere after your change from `vector` to `set`. I suggest to remove it.

2022-10-19 16:53 UTC, jougs commented on nestkernel/secondary_event.h
>   * with the SecondaryEvent in question.
Please also remove the reference to the function here.

2022-10-19 16:53 UTC, jougs commented on nestkernel/secondary_event.h
> +
```suggestion
```

2022-10-19 16:53 UTC, jougs commented on nestkernel/secondary_event.h
>    }
Remove.

2022-10-19 16:53 UTC, jougs commented on nestkernel/target_table_devices_impl.h
> +  for ( auto cit = supported_syn_ids.begin(); cit != supported_syn_ids.end(); ++cit )
Why not go all the way (also renaming the name `cit` [standing for `const_iterator`] to a more meaningful `syn_id`)?
```suggestion
  for ( auto& syn_id : e.get_supported_syn_ids() )
```

2022-10-20 07:34 UTC, heplesser approved these changes
@med-ayssar Thanks! I agree with all suggestions by @jougs. To simplify the workflow, I approve now, assuming that @jougs will only approve once you have followed up on his suggestions.

2022-10-24 11:36 UTC, jougs approved these changes

2022-10-24 11:37 UTC, merged