Fix memory leak with `ResetKernel`
nest/nest-simulator pull request #2520
Opened 2022-11-02 09:51 UTC by hakonsbm

Nodes are created with `new` in `GenericModel`:
https://github.com/nest/nest-simulator/blob/d7ef15baf1ce6b4453a10a0b9708b4e9477abc56/nestkernel/genericmodel.h#L154-L158

Then the node pointers are stored in `memory_` in `Model`. However the nodes are never deleted, which leads to a memory leak when calling `ResetKernel`. With only a few thousand nodes, calling `ResetKernel` multiple times can add up to hundreds of MB of leaked memory.

This PR puts Node pointers in smart pointers within `memory_`, so that the Nodes are automatically deleted when the model is destroyed. The explicit call to the node destructor in `NodeManager` is removed because it interferes with the deletion of the nodes at the end of `Model`s lifetime. This fixes #2519. @ChenK19 Can you check if #2512 is fixed by this as well?

2022-11-02 10:32 UTC, nicolossus approved these changes
LGTM!

2022-11-02 10:50 UTC, heplesser commented
Is there any performance effect of replacing a normal with a smart pointer?

2022-11-02 12:27 UTC, hakonsbm commented
@heplesser `Create` with this branch appears to be initially slightly slower (~4 % for 1e6 nodes), but faster after the first `ResetKernel` (~55 % s for 1e6 nodes).

2022-11-03 07:36 UTC, heplesser commented
> @heplesser `Create` with this branch appears to be initially slightly slower (~4 % for 1e6 nodes), but faster after the first `ResetKernel` (~55 % s for 1e6 nodes).

Are there any effects on simulation time? I assume that smart pointers take more memory (reference counting needs to happen somewhere) and thus worry that they are cached less effectively, so that neuron access during spike delivery might become less efficient. And since neurons are created in a single place and deleted in a single place, I don't think we really need smart pointers.

I think in #2316 we just overlooked the need for destruction when we went away from the memory `pool`.  In the longer run, we should keep [this comment by @jougs](https://github.com/nest/nest-simulator/pull/2316#pullrequestreview-901821003) in mind.

2022-11-03 07:43 UTC, heplesser requested changes
I think we can solve this without smart pointers and the performance and memory cost they imply.

2022-11-03 07:43 UTC, heplesser commented on nestkernel/model.h
> -  std::vector< std::vector< Node* > > memory_;
I would suggest to see if we can stick to a plain `Node*` here.

2022-11-03 07:43 UTC, heplesser commented on nestkernel/node_manager.cpp
> -    }
Here, we should delete nodes explicitly:
```c++
const auto tid = kernel().vp_manager.get_thread_id();
for ( auto node : local_nodes_[ tid ] )
{
  delete node;
}
local_nodes_[ tid ].clear();

2022-11-04 15:46 UTC, heplesser commented
I just did a little test, comparing a program filling a vector with 2^10 `*int` vs `std::shared_ptr<int>`, using g++12 and clang++14. In both cases, the shared pointer takes very close to 40B extra memory per vector element compared to a plain pointer. 

For more on the implementation in the gcc case, see https://gcc.gnu.org/onlinedocs/libstdc++/manual/memory.html#std.util.memory.shared_ptr.

2022-11-10 12:32 UTC, heplesser approved these changes

2022-11-10 12:33 UTC, merged