Refactor collocate_spike_data_buffers
nest/nest-simulator pull request #2522
Opened 2022-11-03 17:18 UTC by med-ayssar

Making `for-loops` iterating over `n` dimensional vector easier to read in the `EventDeliveryManager::collocate_spike_data_buffers_`

2022-11-30 21:26 UTC, heplesser requested changes
@med-ayssar Thanks, makes for much more readable code. Just one renaming suggestion.

2022-11-30 21:26 UTC, heplesser commented on nestkernel/event_delivery_manager.cpp
> +  for ( auto& it : spike_register )
How about `spikes` instead of `it`?

2022-12-01 20:42 UTC, heplesser approved these changes

2022-12-02 09:00 UTC, jougs commented
I don't think I'm a good reviewer here. @suku248, @mlober could you maybe have a look or suggest someone more knowlegeable? Thanks!

2022-12-02 10:21 UTC, mlober requested changes
@suku248 and I have just discussed your changes. Calling the outer iterator `spikes` can be misleading. It should be clear from the variable name that it is an iterator over the writing threads, especially since you replaced the type with `auto`. Calling it something like e.g.`iter_spikes_per_writing_thread` would make this more clear.

2022-12-02 12:26 UTC, heplesser requested changes
Hi @med-ayssar! Here some renaming suggestions by @suku248 and me.

2022-12-02 12:26 UTC, heplesser commented on nestkernel/event_delivery_manager.cpp
> +  for ( auto& spikes : spike_register )
How about
```suggestion
  for ( auto& emitted_spikes_per_thread : emitted_spikes_register )
```

2022-12-02 12:26 UTC, heplesser commented on nestkernel/event_delivery_manager.cpp
> +    for ( unsigned int lag = 0; lag < ( spikes )[ tid ].size(); ++lag )
```suggestion
    for ( unsigned int lag = 0; lag < emitted_spikes_per_thread[ tid ].size(); ++lag )
```

2022-12-02 12:26 UTC, heplesser commented on nestkernel/event_delivery_manager.cpp
> +      for ( auto& emitted_spike : ( spikes )[ tid ][ lag ] )
```suggestion
      for ( auto& emitted_spike : emitted_spikes_per_thread[ tid ][ lag ] )
```

2022-12-02 12:26 UTC, heplesser commented on nestkernel/event_delivery_manager.cpp
> +          spike_to_send.set( emitted_spike, lag );
```suggestion
          send_buffer[ send_buffer_position.idx( rank ) ].set( emitted_spike, lag );
```

2022-12-06 09:51 UTC, heplesser approved these changes

2022-12-06 09:54 UTC, mlober approved these changes

2022-12-06 10:05 UTC, med-ayssar commented
I have done slightly extra changes than requested. Please review again!

2022-12-06 10:14 UTC, heplesser approved these changes

2022-12-06 10:46 UTC, merged