Revising comments on Event class
nest/nest-simulator pull request #2538
Opened 2022-11-28 15:40 UTC by heplesser

This PR provides updated developer documentation for the `Event` class. It thus fixes #129. At a later stage, the `Event` class hierarchy should be reviewed fully.

2022-11-28 18:07 UTC, jessica-mitchell requested changes
@heplesser thanks for looking at this ancient issue; I just have some minor fixes from my side.

2022-11-28 18:07 UTC, jessica-mitchell commented on nestkernel/event.h
> + * Encapsulate information sent between Nodes.
```suggestion
 * Encapsulate information sent between nodes.
```

2022-11-28 18:07 UTC, jessica-mitchell commented on nestkernel/event.h
> + * Encapsulate information sent between Nodes.
I think nodes should not be capitalized, even if the class is. It seems to me most text we have regarding nodes is lower case.

2022-11-29 13:30 UTC, med-ayssar commented
Looks good to me.

2022-11-29 13:30 UTC, med-ayssar approved these changes

2022-11-29 15:52 UTC, heplesser commented
@jessica-mitchell Thanks for your suggestions, I have accepted them all.

2022-11-29 18:36 UTC, jessica-mitchell approved these changes

2022-11-29 20:24 UTC, heplesser commented
Since the test failure is due to causes entirely unrelated to this PR, I merge in spite of one failing test case.

2022-11-29 20:24 UTC, merged