Improve documentation on some HH models
nest/nest-simulator pull request #2539
Opened 2022-11-28 20:59 UTC by heplesser

This PR fixes #329 by making the documentation of the spike-emission mechanism of `hh_cond_exp_traub` even more visible and also fixes documentation for `hh_cond_beta_gap_traub`. Further work on better spike detection methods for these models seems not warranted at this time, also to not break the behaviour of existing code.

2022-11-29 08:29 UTC, jessica-mitchell requested changes
thanks @heplesser just a few minor notes.

2022-11-29 08:29 UTC, jessica-mitchell commented on models/hh_cond_beta_gap_traub.h
> +This model is derived from ``hh_conda_exp`` model, but supports double-exponential-shaped
```suggestion
This model is derived from the ``hh_conda_exp`` model, but supports double-exponential-shaped
```

2022-11-29 08:29 UTC, jessica-mitchell commented on models/hh_cond_beta_gap_traub.h
> +(beta-shaped) synaptic conductances and also support gap junctions. The model is originally
```suggestion
(beta-shaped) synaptic conductances and also supports gap junctions. The model is originally
```

2022-11-29 08:29 UTC, jessica-mitchell commented on models/hh_cond_exp_traub.h
> +   spike, it is essential to chose a sufficiently long refractory period.
```suggestion
   spike, it is essential to choose a sufficiently long refractory period.
```

2022-11-29 08:29 UTC, jessica-mitchell commented on models/hh_cond_exp_traub.h
> +   To avoid that this leads to multiple spikes during the falling flank of a
```suggestion
   To avoid multiple spikes from occurring during the falling flank of a
```

2022-11-29 08:29 UTC, jessica-mitchell commented on models/hh_cond_beta_gap_traub.h
> +   To avoid that this leads to multiple spikes during the falling flank of a
```suggestion
   To avoid multiple spikes from occurring during the falling flank of a
```

2022-11-29 08:29 UTC, jessica-mitchell commented on models/hh_cond_beta_gap_traub.h
> +   spike, it is essential to chose a sufficiently long refractory period.
```suggestion
   spike, it is essential to choose a sufficiently long refractory period.
```

2022-11-29 15:55 UTC, heplesser commented
@jessica-mitchell Thank you for your suggestions, all accepted.

2022-11-29 18:37 UTC, jessica-mitchell approved these changes

2022-12-01 11:44 UTC, clinssen approved these changes

2022-12-01 12:26 UTC, merged