Documentation UX revamp and internal CMake restructuring
nest/nest-simulator pull request #2544
Opened 2022-11-30 11:21 UTC by Helveg

This PR aims to present users with a simple streamlined approach to building the documentation. A user requests which documentation they are interested in by toggling CMake flags for documentation types aimed at certain target audiences, and CMake figures out which documentation targets need to be configured for that. Documentation is generated either implicitly upon installation (`make install`), or explicitly by using `make docs`, or any of the subtargets, but the subtargets aren't considered public features.

Documentation targets are:

* `sphinxdocs`: Uses Sphinx to generate the html documentation, and lots of stuff happens, see comment in code.
* `doxygendocs`: Uses Doxygen to generate the dev docs.
* There is a legacy block for SLI docs, that I didn't refactor as SLI is removed soon.

Documentation flags are:

* `with-userdoc`: Toggles the user documentation, on by default. 
* `with-devdoc`: Toggles the developer documentation, off by default.

## User stories

* I want to install NEST
  * Userdocs are generated and installed along with the NEST library
* I want to turn off this documentation
  * I pass `-Dwith-userdoc=OFF`
* I want to have developer documentation
  * I pass `-Dwith-devdoc=ON`
* I want to build the docs, not NEST
  * I use `make docs` instead of `make install`

closes #1905

2022-11-30 14:08 UTC, Helveg commented
Since building the user documentation brings in a lot of additional build time and dependencies, that need to be installed from different source (apt, pip, built from source, ...) and the ReadTheDocs documentation is more accessible, and more convenient, and we opted to turn off the local build of the documentation.

2022-11-30 17:07 UTC, heplesser approved these changes

2022-11-30 21:15 UTC, jessica-mitchell commented
@Helveg thanks for this PR
the docs seem to build correctly but there is this error at the end of the for userdocs build:

``` 
cmake -Dwith-userdoc=ON ~/Work/repo/nest-simulator/
make docs
```

![image](https://user-images.githubusercontent.com/3313313/204907505-b336dfb1-9108-4d7e-b2dc-5eb3fce19207.png)



the devdoc flag does not elicit any errors.

2022-11-30 21:17 UTC, Helveg commented
I can't reproduce this. Do you have the proper file permissions to execute this file, is it executable? If I'm interpreting the image correctly, it looks like it's trying to run `resolve_includes.py` as a shell script, which is not something that happens for me?

2022-12-01 10:48 UTC, jessica-mitchell requested changes
thanks @Helveg I just have a few changes

2022-12-01 12:52 UTC, Helveg commented on doc/htmldoc/developer_space/workflows/documentation_workflow/user_documentation_workflow.rst
> +If you use pip, install ``pandoc`` from your platform's package manager (e.g. apt):
The `pandoc` that is available on `pip` does not contain any binaries, it appears to be a Python library only, it doesn't appear to have much in common with the CLI tool `pandoc` that we need here, other than the name and purpose.

2022-12-01 13:07 UTC, jessica-mitchell approved these changes
thanks lgtm!

2022-12-01 13:07 UTC, jessica-mitchell commented on doc/htmldoc/developer_space/workflows/documentation_workflow/user_documentation_workflow.rst
> +If you use pip, install ``pandoc`` from your platform's package manager (e.g. apt):
ok, thanks

2022-12-01 13:55 UTC, merged