Fix various typos
nest/nest-simulator pull request #2568
Opened 2022-12-15 14:59 UTC by JanVogelsang

This PR fixes most of the typos anywhere in the repository (excluding thirdparty). Typos have been either identified by a spellchecker or found while reading code (e.g. forth -> fourth).

2022-12-19 17:42 UTC, nicolossus requested changes
@JanVogelsang Thanks for the housecleaning, I only have a few remarks.

2022-12-19 17:42 UTC, nicolossus commented on doc/htmldoc/faqs/faqs.rst
>     together with PyNEST**. We recently observed that if PyNEST is used
```suggestion
6. **I get a segmentation fault when I use SciPy and PyNEST in the same script**. We recently observed that if PyNEST is used
```

I believe the *where* should be a *when*. I also suggest a more concise formulation.

2022-12-19 17:42 UTC, nicolossus commented on doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +Parametrizing the neurons at creation is more efficient than using
Strictly speaking, the old use of *parameterising* is correct. However, using *parametrizing* instead is fine by me and it might also be more in line with the general spelling style in the documentation.

2022-12-19 17:48 UTC, nicolossus commented on doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +Parametrizing the neurons at creation is more efficient than using
@jessica-mitchell What is your stance on this?

2022-12-20 08:11 UTC, JanVogelsang commented on doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +Parametrizing the neurons at creation is more efficient than using
I think American English is much common in computer science compared to British English, I am not entirely sure about NEST though, given NEST having some British roots as well.

2022-12-20 08:21 UTC, JanVogelsang commented on build_support/check_copyright_headers.py
> +stdout instead, so they can be more easily captured and only printed if
It's an optional comma, doesn't really matter if you put it or not. The language checking tool suggested this comma, which is why I added it there.

2022-12-20 08:39 UTC, jessica-mitchell commented on doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +Parametrizing the neurons at creation is more efficient than using
We try to use American English for NEST; we also have a [style guide](https://nest-simulator.readthedocs.io/en/latest/developer_space/guidelines/styleguide/styleguide.html#doc-styleguide) to help with such decisions

Note, however, it should be _parameterizing_

2022-12-20 08:43 UTC, JanVogelsang commented on doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +Parametrizing the neurons at creation is more efficient than using
I think parametrizing is more fitting here.

2022-12-20 08:45 UTC, JanVogelsang commented on doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +Parametrizing the neurons at creation is more efficient than using
However, the difference between both is so subtle that we might also stick with parameterize.

2022-12-20 10:45 UTC, jessica-mitchell commented on doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +Parametrizing the neurons at creation is more efficient than using
Yes, sorry I shouldnt have implied its incorrect. I was going off of the marginal preference for parameterize based on ngram viewer: 
![image](https://user-images.githubusercontent.com/3313313/208648417-98f5b48a-8f2a-46b9-8989-7d1aa7be8026.png)

2022-12-20 11:06 UTC, JanVogelsang commented on doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +Parametrizing the neurons at creation is more efficient than using
I feel like parametrize is used more often in science though, as [this post](https://english.stackexchange.com/questions/79847/parametrise-or-parameterise-a-curve) also claims, that on mathscinet there are more hits of _parametrize_ compared to _parameterize_. Additionally, pytest itself uses _parametrize_, which we use at various places in the code as well.  
You decide though, which one should I use now? There are 3 occurrences in total which I would have to change then.

2022-12-20 12:23 UTC, jessica-mitchell commented on doc/htmldoc/tutorials/pynest_tutorial/part_2_populations_of_neurons.rst
> +Parametrizing the neurons at creation is more efficient than using
Ok I say just go with parametrize then

2022-12-21 10:13 UTC, nicolossus approved these changes
Thanks!

2022-12-22 12:58 UTC, jessica-mitchell approved these changes
Thanks for getting these dealt with :D

2022-12-22 14:00 UTC, JanVogelsang commented
Are the failing tests known ones? Because the current master branch seems to fail as well, and it's hard to believe that fixing typos could ever break something.

2022-12-22 14:34 UTC, jessica-mitchell commented
@JanVogelsang Yah this is a known issue in master. at least the one failing test on FULL.  I just reran the failed tests to see if both fail again.

2022-12-22 16:55 UTC, nicolossus commented
The failing test_macos should be fixed by #2571. Could you try to merge master into this branch @JanVogelsang?

2023-01-02 09:03 UTC, merged