Make pynestkernel compatible with NumPy 1.24
nest/nest-simulator pull request #2571
Opened 2022-12-20 08:20 UTC by heplesser

This fixes #2570 following the suggestions provided in the NumPy 1.20.0 release notes:  https://numpy.org/doc/stable//release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated

2022-12-20 08:36 UTC, Helveg approved these changes
OK! just wondering why we compare to the "C types" with `np.bool_` and `np.int_` and not the Python types bool and int? The article said the replacement was identical

2022-12-20 15:15 UTC, heplesser commented
> OK! just wondering why we compare to the "C types" with `np.bool_` and `np.int_` and not the Python types bool and int? The article said the replacement was identical

I have changed to plain data types now.

2022-12-20 20:32 UTC, clinssen requested changes

2022-12-20 20:32 UTC, clinssen commented on pynest/pynestkernel.pyx
>              elif numpy.issubdtype(array.dtype, numpy.integer):
Please do a grep for "np.float", "numpy.float", ".int", etc., there are a few more occurrences.

2022-12-20 21:42 UTC, heplesser commented on pynest/pynestkernel.pyx
>              elif numpy.issubdtype(array.dtype, numpy.integer):
`numpy.integer` and `numpy.floating` are base classes and thus sensible to use here, see https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.integer. I did not find any further occurrences of `np.float`, `numpy.float` or `.int`.

2022-12-20 22:36 UTC, clinssen commented on pynest/pynestkernel.pyx
>              elif numpy.issubdtype(array.dtype, numpy.integer):
OK, in that case I think all other occurrences look sensible. Cheers!

2022-12-20 22:36 UTC, clinssen approved these changes

2022-12-21 11:44 UTC, Helveg approved these changes

2022-12-21 12:11 UTC, merged