Replace while-loop with C++ find_if function
nest/nest-simulator pull request #2578
Opened 2023-01-09 15:13 UTC by med-ayssar

2023-01-12 11:49 UTC, jougs reviewed
Just some minor cleanup.

2023-01-12 11:49 UTC, jougs commented on nestkernel/universal_data_logger.h
> +    [ &mm_node_id ]( const DataLogger_& dl ) { return dl.get_mm_node_id() == mm_node_id; } );
I think there's no need to repeat the name here. `[ & ]` captures all variables used in the lambda by reference.

```suggestion
    [ & ]( const DataLogger_& dl ) { return dl.get_mm_node_id() == mm_node_id; } );
```

2023-01-12 11:49 UTC, jougs commented on nestkernel/universal_data_logger.h
> +
```suggestion
```

2023-01-12 12:28 UTC, jougs approved these changes
:+1:

2023-01-17 10:08 UTC, hakonsbm requested changes

2023-01-17 10:08 UTC, hakonsbm commented on nestkernel/universal_data_logger.h
> +  auto item = std::find_if( data_loggers_.begin(),
```suggestion
  const auto item = std::find_if( data_loggers_.begin(),
```

2023-01-17 12:02 UTC, hakonsbm approved these changes
Thanks!

2023-01-17 12:02 UTC, merged