Separated checks
nest/nest-simulator pull request #2590
Opened 2023-01-17 09:14 UTC by terhorstd

These changes decompose the `build_ci.sh` into separate steps to be run by the Github Runner. This allows for a better overview and easier management of job dependencies, matrix jobs, etc.

2023-02-01 10:41 UTC, jougs requested changes
Very nice!

Looking through it, I think it would be useful to [split](https://stackoverflow.com/questions/59813998/github-actions-splitting-workflow-file) the new and longer [.github/workflows/nestbuildmatrix.yml](https://github.com/nest/nest-simulator/pull/2590/files#diff-89de577a8ded6cb539f7c66e2989d107870f3dc0d96a3f12d40fd8ccd1c92687) into multiple files.

Maybe one for the static checks, one for Linux builds, one for mac OS builds and then one for each downstream action after that (tests, packaging, ...)

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +name: "Test suite"
What is this name about? If it the title overarching *all* CI jobs, I think it should rather be something like "NEST CI jobs", as "Test suite" implies that this is running (only) our [testsuite](https://github.com/nest/nest-simulator/tree/master/testsuite).

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +        #  config: https://raw.githubusercontent.com/terhorstd/nest-simulator/separated-checks-vale/.vale.ini
```suggestion
```

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
```suggestion
```
Probably all lines in this repository are "required", otherwise they would not be here...

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +        # TODO: doc/auto_examples and doc/models need to be added here, but exists only after a `make html`
Can this TODO be resolved?

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +          # to overcome rate limiting
```suggestion
```

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +    #needs: [pydocstyle, pycodestyle, pylint, flake8]
```suggestion
```

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +
```suggestion
```

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +      matrix: # *buildmatrix
```suggestion
      matrix:
```

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +    #if: ${{ always() }}
```suggestion
```

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +        # Run flake8 on the entire repository
```suggestion
```

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
>    static_checks:
I think this one can (and should) be removed now.

2023-02-01 10:41 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +  build_linux_oldscript:
Please remove

2023-04-25 08:59 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +      - name: "Install dependencies"
Is this dependency required? Same comment for the next job.

2023-04-25 08:59 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +        #if: '${{ matrix.NEST_BUILD_TYPE }} == "FULL"'
```suggestion
```

2023-04-25 08:59 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +        # openmp, mpi, python, gsl, ltdl, boost, sionlib, libneurosim, optimize, warning, userdoc, music
```suggestion
        # openmp, mpi, python, gsl, ltdl, boost, sionlib, libneurosim, optimize, warning, userdoc, music
```
```suggestion
```

2023-04-25 08:59 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +
```suggestion
```

2023-04-25 08:59 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +  pytest-linux:
Since we are still working on porting the SLI tests to python, we can turn this job off until then.

2023-04-25 08:59 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +          ls -lsia
Duplicate step

2023-04-25 08:59 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +          ls -lsia
```suggestion
```

2023-04-25 08:59 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +    if: false
Could we enable this and also replace the calls to `ci_build.sh`?

2023-04-25 08:59 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +    uses: conda-forge/nest-simulator-feedstock/.github/workflows/nest_trigger.yml@f9a89c898b4481931fe6b587c05547b42e758e46
Could we add build steps to this?

2023-04-25 11:22 UTC, Helveg commented on doc/htmldoc/_ext/VersionSyncRole.py
> +        except KeyError:
That one should be triggered only if you use `except:` or `except Exception:` might trigger `too broad exception clause`

2023-04-25 12:46 UTC, jougs commented on doc/htmldoc/_ext/VersionSyncRole.py
> +        except KeyError:
OK. Thanks for the clarification!

2023-04-26 07:24 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +      - name: "Install Linux system dependencies"
```suggestion
      - name: "Install dependencies"
```

2023-04-26 07:24 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +    if: ${{ always() && !contains(github.event.head_commit.message, 'ci skip') }}
Should `always()` be removed here so that this doesn't run if the previous steps fail?

2023-04-26 07:24 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +      matrix: # &buildmatrix   # when enabled raises WorkflowError: Anchors are not currently supported. Remove the anchor 'buildmatrix'
```suggestion
```

2023-04-26 07:24 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +        cpp_compiler: ["gcc"]   #, "clang"]
```suggestion
        cpp_compiler: ["gcc"]
```

2023-04-26 07:24 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +      # - name: "Upload binary artifacts"
Should we remove this? Same applies for the mac step.

2023-04-26 14:13 UTC, pnbabu approved these changes
Looks good, thanks!

2023-04-26 14:15 UTC, jougs approved these changes
Much better than what we had before, thus approving even though there are still things to iron out.

@terhorstd, @clinssen: Thanks for all the hard work on this :heart:

2023-04-27 11:30 UTC, clinssen commented
Blocked by #2720.

2023-04-28 14:07 UTC, merged