Add documentation about deadlock in parallel computing
nest/nest-simulator pull request #2758
Opened 2023-05-02 08:13 UTC by jessica-mitchell

This PR add a note in the documentation in the distributed computing section of the parallel computing page, regarding the issue resolved in  #2749.

See output [here](https://nest-test.readthedocs.io/en/docs-mpi-update/hpc/parallel_computing.html#using-distributed-computing)

2023-05-02 09:29 UTC, nicolossus requested changes
@jessica-mitchell Thanks! I have some minor suggestions for the example code, but overall this looks good and is a very useful addition to the documentation.

2023-05-02 09:29 UTC, nicolossus commented on doc/htmldoc/hpc/parallel_computing.rst
> +                nest.rng_seed))
```suggestion
      if nest.Rank() == 0:
            rng_seed = nest.rng_seed
            print(f"RNG seed: {rng_seed}")
```

I think for the purpose of illustration, the `nest.*` call should be on a a line of its own. This also makes the comparison with the next code block more clear. Moreover, we should use f-strings.

2023-05-02 09:29 UTC, nicolossus commented on doc/htmldoc/hpc/parallel_computing.rst
> +        print('RNG seed: {}'.format(rng_seed))
```suggestion
     rng_seed = nest.rng_seed
     if nest.Rank() == 0:
        print(f"RNG seed: {rng_seed}")
```
The `nest.*` call should also be included here.

2023-05-02 09:59 UTC, nicolossus approved these changes

2023-05-02 10:19 UTC, JoseJVS reviewed
Great! This is exactly what was needed. Perhaps could you add a sentence like:
```
The PyNEST API was designed so that all parallel operations are handled through the nestkernel, hence the users don't need to handle MPI communication from the python script.
Ideally the script should be written in a serial manner, however if specific operations unrelated to the simulation execution are needed, the NEST API offers the Rank() function to retrieve the MPI rank of the process and handle process specific tasks.
Note that one should never call any ....
```

So that it is clear that parallelization is fully handled from the kernel and not the python script.

2023-05-02 18:03 UTC, heplesser requested changes
@jessica-mitchell Thanks for this PR! I wonder if it would not work even better if the "Important" box came at the end of the "MPI related commands" section that is now just below the "Important" box. Also, in the "Run distributed simulations" section, an "r" is missing in "distibuted simulation scripts". Could you fix that as part of this PR?

Concerning the suggestion by @JoseJVS, I think this is pretty much covered if one looks at the "Using distributed computing" section as a whole, so adding another sentence would make it a bit repetitive.

2023-05-03 09:24 UTC, heplesser approved these changes

2023-05-03 09:24 UTC, merged