Refactor SLI test for spike generator to Python
nest/nest-simulator pull request #2761
Opened 2023-05-02 12:11 UTC by pnbabu

2023-05-15 10:36 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_generator.py
> +    nptest.assert_array_equal(spike_times, expected_spike_times)
```suggestion
def test_spike_generator(prepare_kernel, spike_times, allow_offgrid_times, expected_spike_times):
    sg_params = {
        "precise_times": False,
        "spike_times": spike_times,
        "allow_offgrid_times": allow_offgrid_times,
        "origin": 0.0,
        "start": 0.0,
        "stop": 6.0,
    }

    sg = nest.Create("spike_generator", sg_params)
    sr = nest.Create("spike_recorder", {"time_in_steps": True})
    nest.Connect(sg, sr, syn_spec={"delay": 1.0, "weight": 1.0})

    nest.Simulate(10.0)

    actual_spike_times = sr.events["times"]
    nptest.assert_array_equal(actual_spike_times, expected_spike_times)
```

2023-05-15 11:17 UTC, nicolossus requested changes
@pnbabu Thanks, this looks good overall. I've made some suggestions for making the test code a bit more compact and formatted according to the Black formatter. 

The SLI versions of these tests have some documentation; can you please also add docstrings with a short descriptions for each test?

2023-05-15 11:17 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_generator.py
> +    assert spike_times == pytest.approx(expected_spike_times)
```suggestion
def test_spike_generator_set_and_get(prepare_kernel, sg_params, expected_spike_times):
    sg = nest.Create("spike_generator")
    sg.set(sg_params)
    actual_spike_times = sg.get("spike_times")
    nptest.assert_almost_equal(actual_spike_times, expected_spike_times, decimal=5)
```

2023-05-15 11:17 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_generator.py
> +    assert spike_times == pytest.approx(expected_spike_times)
```suggestion
def test_spike_generator_precise_times_different_resolution(h, expected_spike_times):
    nest.ResetKernel()
    nest.resolution = h

    sg_params = {
        "precise_times": True,
        "spike_times": [0.1, 5.0, 5.3, 5.300001, 5.399999, 5.9, 6.0, 9.3],
        "origin": 0.0,
        "start": 5.0,
        "stop": 6.0,
    }
    sg = nest.Create("spike_generator", sg_params)
    sr = nest.Create("spike_recorder")
    nest.Connect(sg, sr, syn_spec={"delay": 1.0, "weight": 1.0})

    nest.Simulate(7.0)

    actual_spike_times = sr.events["times"]
    nptest.assert_almost_equal(actual_spike_times, expected_spike_times)
```

2023-06-02 12:28 UTC, heplesser commented
@pnbabu Ping from the NEST Testing meeting!

2023-06-28 07:33 UTC, heplesser commented
@pnbabu Ping!

2023-06-28 07:42 UTC, pnbabu commented
> @pnbabu Ping!

I have applied the suggestions from the code review. I will request a review again.

2023-06-28 07:54 UTC, nicolossus requested changes
@pnbabu Thanks! This now looks mostly good to me, but can you also add the documentation from the SLI version as docstrings describing a bit more what each test actually checks?

2023-06-28 13:51 UTC, nicolossus requested changes
@pnbabu Thanks! I have a few nitpicks but once they are addressed I will be happy :)

2023-06-28 13:51 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_generator.py
> +    be emitted
```suggestion
    Here, the spike time is within ``tic/2`` of step 100, rounded down to 100 thus not in the future;
    spike will not be emitted.
```

2023-06-28 13:51 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_generator.py
> +    This test checks the future spike times with "precise_times" set to True.
```suggestion
    Ensure correct behavior of future spike times with ``precise_times`` set to ``True``.
```

2023-06-28 13:51 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_generator.py
> +    This test checks the spike times with "shift_now_spikes" set to True.
```suggestion
    Check spike times with ``shift_now_spikes`` set to ``True``.
```

2023-06-28 13:51 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_generator.py
> +    This test ensures the exclusivity between options "precise_times" and "shift_now_spikes".
```suggestion
    Ensure exclusivity between options ``precise_times`` and ``shift_now_spikes``.
```

2023-06-28 13:51 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_generator.py
> +    - set and get with "shift_now_spikes" set to True
```suggestion
    Test the ``set`` and ``get`` functions of ``spike_generator``.
    
    The test checks ``set`` and ``get`` with:
    - default values.
    - ``allow_offgrid_times`` set to ``True``.
    - ``precise_times`` set to ``True``.
    - ``shift_now_spikes`` set to ``True``.
```

2023-06-28 13:51 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_generator.py
> +    This test checks the precise times of spikes for different simulation resolution values.
```suggestion
    Test the precise times of spikes for different resolutions.
```

2023-06-28 18:47 UTC, nicolossus approved these changes

2023-06-29 09:46 UTC, merged