Get Sphinx build working in CI
nest/nest-simulator pull request #2763
Opened 2023-05-02 19:33 UTC by jessica-mitchell

This  PR updates the nestbuildmatrix for sphinx-rtd so that it builds Sphinx.

2023-05-03 07:38 UTC, terhorstd requested changes
Hey! Thanks for the fixes! – Maybe add some comments with a bit of context, so that the next person looking at this understands the motivation.

2023-05-03 07:38 UTC, terhorstd commented on .github/workflows/nestbuildmatrix.yml
> +          python-version: 3.8
What is the critical part depending on the old version?

2023-05-03 08:11 UTC, jessica-mitchell commented
@terhorstd I added some comments with links to better explain the install for pandoc and specifying the Python version

2023-05-05 09:31 UTC, terhorstd commented on .github/workflows/nestbuildmatrix.yml
> +          python-version: 3.8
Thanks for adding the comment.

2023-05-05 09:37 UTC, jessica-mitchell commented on .github/workflows/nestbuildmatrix.yml
> +          sudo apt-get install pandoc
I added a comment (See my change) , pip does not lead to broken version, from what I understand is the 'executable' part is not pip installable

2023-05-05 09:45 UTC, terhorstd approved these changes
LGTM! :)

2023-05-05 10:37 UTC, merged