Port `test_spike_poisson_ps` from SLI-2-Py
nest/nest-simulator pull request #2805
Opened 2023-05-24 21:20 UTC by nicolossus

2023-07-04 09:57 UTC, janskaar approved these changes

2023-08-07 14:08 UTC, heplesser requested changes

2023-08-08 10:16 UTC, nicolossus commented on testsuite/pytests/sli2py_stimulating/test_spike_poisson_ps.py
> +    assert np.all(are < 1e-14)
Changed to `numpy.testing` assertion in https://github.com/nest/nest-simulator/pull/2805/commits/75493176e7c5d6b47c9c1fc62b798819585e90a8.

2023-08-08 15:22 UTC, heplesser approved these changes

2023-08-08 15:22 UTC, merged