Port `issue-1305.sli` to Pytest
nest/nest-simulator pull request #2806
Opened 2023-05-24 22:41 UTC by nicolossus

2023-07-03 15:29 UTC, janskaar commented on testsuite/pytests/sli2py_regressions/test_issue_1305.py
> +This set of tests ensures that NEST hcan set small resolutions and deals with
```suggestion
This set of tests ensures that NEST can set small resolutions and deals with
```

2023-07-03 19:07 UTC, janskaar approved these changes

2023-08-07 14:06 UTC, heplesser requested changes
See inline. The precise value of 1e-15 in the test is not important, a relative error of 1e-6 as default for approx is fine.

2023-08-07 14:06 UTC, heplesser commented on testsuite/pytests/sli2py_regressions/test_issue_1305.py
> +    assert abs_diff < 1e-15
Please use `pytest.approx` here.

2023-08-08 09:59 UTC, nicolossus commented on testsuite/pytests/sli2py_regressions/test_issue_1305.py
> +    assert abs_diff < 1e-15
Fixed by https://github.com/nest/nest-simulator/pull/2806/commits/32f111fcd83991a2297ca3323519bf1e77a7873b.

2023-08-08 15:21 UTC, heplesser approved these changes

2023-08-08 15:21 UTC, merged