Port `test_pulsepacket_generator` from SLI-2-Py
nest/nest-simulator pull request #2815
Opened 2023-06-01 13:46 UTC by nicolossus

The PR also improves the formatting of the documentation for `stimulation_device` and `pulsepacket_generator`.

2023-06-05 11:13 UTC, nicolossus commented
@jougs @jessica-mitchell The SLI-2-Py port is quite one-to-one and straightforward. However, in porting the test I noticed some places in the documentation that could be improved by some small changes to the formatting . So far I have only made similar changes to the documentation on files I have touched, see https://github.com/nest/nest-simulator/pull/2813. I will make the corresponding changes elsewhere once we agree on the style.

2023-06-22 07:34 UTC, jessica-mitchell requested changes
Just a minor change, 
and more to @jougs the stimulation_device userdocs in nestkernel has a NOINDEX label, and I don't think it's in Read the docs. I think this should be included somewhere, oder?

2023-06-22 07:34 UTC, jessica-mitchell commented on nestkernel/stimulation_device.h
> +  affects the target's dynamics is :math:`(\textrm{stop}-h, \texrm{stop}]`.
```suggestion
  affects the target's dynamics is :math:`(\textrm{stop}-h, \textrm{stop}]`.
```

2023-06-27 20:24 UTC, jessica-mitchell approved these changes

2023-06-28 08:07 UTC, heplesser commented on testsuite/pytests/sli2py_stimulating/test_pulsepacket_generator.py
> +
```suggestion
def test_number_of_spikes():
    """
    Test that `pulsepacket_generator` emits expected number of spikes.

```

2023-06-28 08:08 UTC, heplesser commented on testsuite/pytests/sli2py_stimulating/test_pulsepacket_generator.py
> +Test parameter setting and statistical correctness of `pulsepacket_generator`.
```suggestion
Test parameter setting and correct number of spikes emitted by `pulsepacket_generator`.
```

2023-06-28 08:09 UTC, heplesser approved these changes

2023-06-28 08:10 UTC, merged