Set correct virtual model name in NEST-SONATA documentation
nest/nest-simulator pull request #2826
Opened 2023-06-07 13:13 UTC by nicolossus

NEST-SONATA uses the `spike_train_injector` as virtual model (used to be `spike_generator`). This PR changes the name of the virtual model to the correct one in places that were overlooked when the switch of models took place.

2023-06-22 13:51 UTC, nicolossus commented
@jessica-mitchell The failing CI was due to a formatting error in master which was fixed by #2837. Could you retrigger the CI?

2023-06-23 11:05 UTC, jessica-mitchell requested changes
Looks good, just one minor suggestion

2023-06-23 11:05 UTC, jessica-mitchell commented on doc/htmldoc/nest_sonata/nest_sonata_guide.rst
> +``virtual`` nodes are modeled as ``spike_train_injector``\s (see :doc:`../models/spike_train_injector`\). NEST requires
```suggestion
``virtual`` nodes are modeled as ``spike_train_injector``\s (see :doc:`the model documentation for spike_train_injector <../models/spike_train_injector>`\). NEST requires
```

2023-06-23 12:48 UTC, jessica-mitchell approved these changes

2023-06-23 12:48 UTC, jessica-mitchell commented
Merging with 1 reviewer as its doc related

2023-06-23 12:49 UTC, merged