Note on using mamba instead of conda
nest/nest-simulator pull request #2923
Opened 2023-09-07 07:40 UTC by steffengraber

#2863 and #2896 show problems in using the NEST conda package and the conda environment file. 
With conda, the installation of NEST and the environment can be very slow, leading to crashes. Mamba (https://mamba.readthedocs.io) speeds up the installation enormously and thus improves the stability of the process. Mamba can be used as a drop-in replacement to conda.
The note draws attention to the problem and should provide a solution. 
Conda remains the standard tool for the time being.
@jessica-mitchell Would be nice if you could have a look.

2023-09-07 10:36 UTC, jessica-mitchell requested changes

2023-09-07 10:36 UTC, jessica-mitchell commented on doc/htmldoc/installation/conda_forge.rst
> +   environment, we recommend using mamba (https://mamba.readthedocs.io).
```suggestion
   environment, we recommend using Mamba (https://mamba.readthedocs.io). 
```

2023-09-07 10:36 UTC, jessica-mitchell commented on doc/htmldoc/installation/conda_forge.rst
> +   environments and can be used as a complete drop-in replacement.
Please apply to all texts

2023-09-10 15:51 UTC, heplesser approved these changes

2023-09-11 08:24 UTC, merged