Adding glif_psc_double_alpha model (2nd attempt)
nest/nest-simulator pull request #2925
Opened 2023-09-07 20:59 UTC by shixnya

Continuation of PR #2861 that was accidentally closed.
The most recent change contains rebasing to the updated upstream/master, and fixing one of the newly added test cases in the updates.

Hopefully, this version passes all of the tests.

2023-09-08 05:43 UTC, heplesser commented
@shixnya @nicolossus No problem to proceed here.
@clinssen @janskaar Could you re-review here quickly?

2023-09-08 07:52 UTC, nicolossus approved these changes
LGTM!

2023-09-08 13:58 UTC, janskaar approved these changes
Everything looks good to me.

2023-09-12 08:03 UTC, clinssen approved these changes

2023-09-12 14:15 UTC, jessica-mitchell requested changes
Thanks @shixnya , I just a have couple of minor changes for the docs

2023-09-12 14:15 UTC, jessica-mitchell commented on pynest/examples/glif_psc_double_alpha_neuron.py
> +Current-based generalized leaky integrate and fire (GLIF) neuron with double alpha
```suggestion
Current-based generalized leaky integrate and fire (GLIF) neuron with double alpha \
```

2023-09-12 14:15 UTC, jessica-mitchell commented on pynest/examples/glif_psc_double_alpha_neuron.py
> +Current-based generalized leaky integrate and fire (GLIF) neuron with double alpha
The title doesn't render in HTML if it goes over two lines without the `\`

2023-09-12 14:15 UTC, jessica-mitchell commented on pynest/examples/glif_psc_double_alpha_neuron.py
> +difference from the ``glif_psc`` neuron model.
```suggestion
differences from the ``glif_psc`` neuron model.
```

2023-09-14 07:11 UTC, jessica-mitchell approved these changes
thanks!

2023-09-14 20:51 UTC, merged

2023-09-15 17:50 UTC, shixnya commented
Thank you so much, all, for your help!