bug fix iaf_psc_exp_multisynapse / sli2py test_iaf_psc_exp_multisynapse
nest/nest-simulator pull request #2986
Opened 2023-11-14 10:29 UTC by janskaar

Before, S_.current_ was computed _before_ the updating individual synaptic ports, causing them to be 1 time step behind. Additionally, it was only computed when the neuron was not refractory, while the individual synaptic ports were updated every time step. Moving the S_.current_ computation down a few lines fixes this.

Port test_iaf_psc_exp_multisynapse.sli to py

2023-11-16 10:14 UTC, heplesser requested changes
@janskaar Good catch! I have an alternative solution for summing the currents and some suggestions for the tests. The same problem applies to `iaf_psc_alpha_multisynapse`.  I think it would be a good idea to fix both neurons within this PR.

2023-11-16 10:14 UTC, heplesser commented on testsuite/pytests/test_iaf_psc_exp_multisynapse.py
> +        nest.Connect(sg, nrn, conn_spec="one_to_one", syn_spec=syn_spec)
A more elegant solution:

```suggestion
    for syn_idx, (delay, weight) in enumerate(zip(delays, weights)):
        syn_spec = {
            "synapse_model": "static_synapse",
            "delay": delay,
            "weight": weight,
            "receptor_type": syn_idx + 1,
        }

        nest.Connect(sg, nrn, conn_spec="one_to_one", syn_spec=syn_spec)
```

2023-11-16 10:14 UTC, heplesser commented on testsuite/pytests/test_iaf_psc_exp_multisynapse.py
> +    I_syn = np.sum([mm.get("events", f"I_syn_{i}") for i in range(1, 5)], axis=0)
This weakens the test and explains why the wrong `current_` was not detected by the tests. We should test the `I_syn` recordable here (not sure if it needs and extra `[0]` at the end):
```suggestion
    I_syn = mm.get("events", "I_syn")
```

2023-11-16 10:14 UTC, heplesser commented on testsuite/pytests/test_iaf_psc_exp_multisynapse.py
> +    nptest.assert_array_almost_equal(mm.get("events", "I_syn_4"), I_syns_analytical[3])
```suggestion
    for idx, I_syn_analytical in enumerate(I_syns_analytical):
        nptest.assert_array_almost_equal(mm.get("events", f"I_syn_{idx+1}"), I_syn_analytical)
```

2023-11-16 10:19 UTC, heplesser requested changes
The new test should got to `pytest/sli2py_models`.

2023-11-22 12:18 UTC, janskaar commented on testsuite/pytests/test_iaf_psc_exp_multisynapse.py
> +    vals[nonzero_inds] = np.exp(-t[nonzero_inds] / tau_syn)
Changed this to a slighly different solution

2023-11-23 10:50 UTC, heplesser requested changes
@janskaar This looks fine now, but there seem to be some problems with formatting. Could you fix those? And how about a corresponding test for alpha multisynapse? Is that in a separate PR?

2023-11-25 13:45 UTC, janskaar commented
> @janskaar This looks fine now, but there seem to be some problems with formatting. Could you fix those? And how about a corresponding test for alpha multisynapse? Is that in a separate PR?

Formatting should be fixed now. The alpha multisynapse test was merged a couple of weeks ago, but I have updated it to be more in line with this one now.

2023-11-27 12:56 UTC, janskaar commented
@heplesser Sorry, just noticed that test_mini_brunel_ps.sli fails, but only on MacOS. Have you encountered something like this before? It's for a completely different neuron model, so it's difficult to see why it should fail here.

2023-11-28 14:54 UTC, heplesser commented
@otcathatsya Ping!

2023-12-12 09:31 UTC, otcathatsya approved these changes
Looks good! Do we have a preference for which approximate comparison method to use? We have quite a few `pytest.approx` and I just saw that numpy's `assert_almost_equal` works with absolute decimal places instead, though in this case they'd work interchangeably too.

2023-12-12 10:45 UTC, heplesser commented
> Looks good! Do we have a preference for which approximate comparison method to use? We have quite a few `pytest.approx` and I just saw that numpy's `assert_almost_equal` works with absolute decimal places instead, though in this case they'd work interchangeably too.

I don't think we have made a definite decision. I am not certain how pytest.approx works on NumPy arrays, because `==` between arrays returns an array of bools, not a single truth value.

2023-12-12 10:45 UTC, merged