Add `shellcheck` and `pre-commit` to CI jobs
nest/nest-simulator pull request #3002
Opened 2023-11-21 13:45 UTC by terhorstd

This is an addendum to #2880 adding a `pre-commit` run also to the CI pre-build checks.
The `shellcheck` is also added separately to address language specific linters on the same level.

Related PRs are:
* #2936 
* #2968
* #2996

2024-06-20 12:09 UTC, heplesser requested changes
See comments and suggestions.

2024-06-20 12:09 UTC, heplesser commented on .github/workflows/nestbuildmatrix.yml
> +      - name: "Run shellcheck..."
```suggestion
      - name: "Run pre-commit ..."
```

2024-06-20 12:09 UTC, heplesser commented on .github/workflows/nestbuildmatrix.yml
> +  pre-commit-hooks:
Check if this has already been integrated.

2025-01-21 17:36 UTC, terhorstd commented on .github/workflows/nestbuildmatrix.yml
> +  pre-commit-hooks:
This is now fixed with the correct `find . -iname "*.sh" -o -iname "*.sh.in" | …`. Have a look also into `.pre-commit-config.yaml` where currently a hand-written list needs to be maintained.

2025-01-22 09:45 UTC, heplesser reviewed
@terhorstd This looks good, but see the few inline comments. Did you run the shell scripts that have been modified significantly and which are not run by the CI, e.g., run_micrcocircuit and run_examples?

2025-01-22 09:45 UTC, heplesser commented on .github/workflows/nestbuildmatrix.yml
> +  pre-commit-hooks:
@terhorstd Given that we also run the pre-commit tests just below, does this not lead to running shellcheck twice in the test process?

2025-01-22 09:45 UTC, heplesser commented on .github/workflows/nestbuildmatrix.yml
> +    # This check makes sure the repository is always consistent NL line endings.
What does `NL` mean? There is also some grammatical problem in the sentence.

2025-01-22 09:45 UTC, heplesser commented on doc/htmldoc/static/img/EBRAINS.svg
Why does git show that all SVG files here have been replaced by identical-looking files?

2025-01-22 09:53 UTC, heplesser commented
I am exploring the test failure on macOS.

2025-01-22 10:22 UTC, terhorstd commented on .github/workflows/nestbuildmatrix.yml
> +  pre-commit-hooks:
yes, and with potentially different settings. The idea behind was that pre-commit tests if the developer has run the checks, but we still have each test separately in the CI overview.

`clang-format` is another candidate and that basically makes sure that our clang versions don't differ between developer and CI machines.

Currently whole process is 49 seconds, could be much less if we add caching of the pre-commit environments.

2025-01-22 10:31 UTC, terhorstd commented on doc/htmldoc/static/img/EBRAINS.svg
A single newline at the end was changed. Should I add an ignore for those or are we fine with this?

2025-01-22 11:13 UTC, terhorstd commented
The reason for the MacOS failure is described in https://stackoverflow.com/a/752893. And I think I found a workaround.

2025-01-22 11:49 UTC, heplesser commented on .github/workflows/nestbuildmatrix.yml
> +  pre-commit-hooks:
OK, thanks for the explanation.

2025-01-22 11:51 UTC, heplesser commented on doc/htmldoc/static/img/EBRAINS.svg
Fine now, since the files now are fixed leave them in.

2025-01-22 11:51 UTC, heplesser commented on .github/workflows/nestbuildmatrix.yml
> +    # in their line endings, i.e. new line, and not carrige return+line feed.
```suggestion
    # in their line endings, i.e. new line, and not carriage return+line feed.
```

2025-01-22 11:53 UTC, heplesser commented on .github/workflows/nestbuildmatrix.yml
> +    # This check makes sure the repository is always consistent NL line endings.
Thanks for the improved implementation!

2025-02-18 08:38 UTC, terhorstd commented
Hey, could you have another look? I think it's ready to go

2025-02-19 15:33 UTC, heplesser requested changes
Hi @terhorstd! I spotted one potential copy-paste-error (but I may have looked at an outdated file version), have one suggestion and one question.

2025-02-19 15:33 UTC, heplesser commented on build_support/install_sionlib.sh
> +SIONLIB_INSTALL_PATH="${1:-${HOME}/.cache/csa.install}"
Are you sure the `csa.install` here is correct? Why not `sionlib.install`?

2025-02-19 15:33 UTC, heplesser commented on examples/run_examples.sh
> +        grep -rl --include='*.sli' 'autorun=true' "${sourcedir}/nest/" >>"$EXAMPLELIST" || true
What is the purpose of `|| true`?

2025-02-19 15:33 UTC, heplesser commented on examples/run_examples.sh
> +    if test -x "/usr/local/bin/gtime"; then
For some reason, I cannot make a suggestion here, but the path should be `/opt/homebrew/bin/gtime` (also below). Homebrew installs everything under `/opt/homebrew` on Apple Silicon.

2025-02-21 16:53 UTC, terhorstd commented on examples/run_examples.sh
> +        grep -rl --include='*.sli' 'autorun=true' "${sourcedir}/nest/" >>"$EXAMPLELIST" || true
If grep does not find the string (i.e. there are not exmples in that directory) then the script exits due to the error code. `true` always returns a successful return-code.

2025-02-21 16:55 UTC, terhorstd commented on examples/run_examples.sh
> +    if test -x "/usr/local/bin/gtime"; then
A nicer way to define this would be a `$(which gtime)` but I don't know if that is correctly found. Could you check?

2025-02-21 16:59 UTC, terhorstd commented on build_support/install_sionlib.sh
> +SIONLIB_INSTALL_PATH="${1:-${HOME}/.cache/csa.install}"
Not shure how you see this, but it has been fixed in https://github.com/nest/nest-simulator/pull/3002/commits/6f937ebcf974557718fd253514e8d38ae25347cc, hence the "(outdated)" above.

2025-02-24 08:27 UTC, heplesser commented on examples/run_examples.sh
> +    if test -x "/usr/local/bin/gtime"; then
Seems to work:
```
(nn) ~> echo $(which gtime)
/opt/homebrew/bin/gtime
```

2025-02-26 10:02 UTC, terhorstd commented on examples/run_examples.sh
> +    if test -x "/usr/local/bin/gtime"; then
Thanks, I added the `which`

2025-02-27 08:30 UTC, heplesser approved these changes

2025-07-30 18:05 UTC, terhorstd commented
I merged master in and fixed the conflicts. Mostly trivial to solve because lines where edited in master where this branch had style updates from the new checks.
Addtionally, the new checks already found inconsistencies sneaking into master, such as [trailling whitespace](https://github.com/nest/nest-simulator/actions/runs/16629959503/job/47056510460#step:5:42), so the added mechanism already has a proof-of-work :-)

2025-08-15 06:57 UTC, merged