Further improve iaf_psc_alpha documentation
nest/nest-simulator pull request #3034
Opened 2023-12-06 09:45 UTC by heplesser

This PR provides default and initial values in parameter tables and splits them into separate tables for parameters and state variables.

2023-12-14 23:07 UTC, ackurth requested changes

2023-12-14 23:07 UTC, ackurth commented on models/iaf_psc_alpha.h
> +**Parameter**   **Default** **Math equivalent**                    **Description**
```suggestion
=============== ================== =============================== ========================================================================
**Parameter**   **Default**        **Math equivalent**             **Description**
```

The changes look good, this clearly improves the documentation.
When I build the docs I see the following:
![nest_doc](https://github.com/nest/nest-simulator/assets/44397333/bd8d5558-cbde-47fd-88ea-58ad7059831a)

I think that in the upper box the ```**math``` is incorrect, isn't it (especially in comparison with the lower one)?
I tried to fix this with my suggestion, but doing this with the GitHub interface was a bit tricky, hope it worked.

2023-12-15 08:09 UTC, heplesser commented
@ackurth Thanks for spotting this, committed now.

2023-12-21 08:06 UTC, jessica-mitchell approved these changes

2023-12-21 08:06 UTC, merged