Updat documentation for ```iaf_psc_exp```
nest/nest-simulator pull request #3084
Opened 2024-02-01 08:53 UTC by ackurth

2024-03-01 15:13 UTC, heplesser requested changes
@ackurth This looks quite good already, but see my inline comments. I would also like to ask for a slight re-ordering of material that you have not touched:

1. Move the last paragraph before the Parameters section ("For conversion ...") before the note on the time constants.
2. Put the material on the two different ways in which the model can handle input into a note as well.

2024-03-01 15:13 UTC, heplesser commented on models/iaf_psc_exp.h
> +   i_{\text{syn, X}}(t) = e^{-\frac{t}{\tau_{\text{syn, X}}}} \Theta(t)
I would include the weight `w` here and in the following equations to ensure that units work out, in the same corresponding way as for `iaf_psc_delta`.

2024-03-01 15:13 UTC, heplesser commented on models/iaf_psc_exp.h
> +``V_min``       :math:`-\infty` mV :math:`V_{\text{min}}`          Absolute lower value for the membrane potential
A bit surprising, but `iaf_psc_exp` does not seem to have `V_min`. Adding it would be a different issue.
```suggestion
```

2024-03-01 15:13 UTC, heplesser commented on models/iaf_psc_exp.h
> +:math:`V_{\text{min}}` as lower bound of :math:`V_\text{m}`.
`iaf_psc_exp` does not seem to have this ...

```suggestion
```

2024-04-24 08:31 UTC, jessica-mitchell commented
Here is link to output on Read the Docs: https://nest-simulator--3084.org.readthedocs.build/en/3084/models/iaf_psc_exp.html

2024-05-07 08:21 UTC, jessica-mitchell commented
@ackurth @heplesser  After some discussion with David D. about models, we noticed that in the original model description, it mentions the stochastic use case - which does not appear to be in this version - is that correct?
> Spiking in this model can be either deterministic (delta=0) or stochastic (delta > 0). In the stochastic case this model implements a type of spike response model with escape noise

2024-06-20 08:26 UTC, jessica-mitchell requested changes
thanks @ackurth, just a couple of minor typos

2024-06-20 08:26 UTC, jessica-mitchell commented on models/iaf_psc_exp.h
> +* a hard threshold (if :math:`\delta=0, see below)
```suggestion
* a hard threshold (if :math:`\delta=0`, see below)
```

2024-06-20 08:26 UTC, jessica-mitchell commented on models/iaf_psc_exp.h
> +	In the stochastic case this model implements a type of spike response model with escape noise.
```suggestion
	In the stochastic case, this model implements a type of spike response model with escape noise.
```

2024-06-20 09:47 UTC, heplesser approved these changes
@ackurth Thanks, this is fine now except for the small details @jessica-mitchell has pointed out. Please merge master so that tests will pass.

2024-06-20 12:31 UTC, jessica-mitchell approved these changes

2024-06-20 12:46 UTC, merged