Align documentation of connection management with connectivity concepts publication (v2)
nest/nest-simulator pull request #3172
Opened 2024-04-04 13:18 UTC by jhnnsnk

This PR replaces #2992, for the discussion refer to the original PR.

2024-04-04 14:01 UTC, heplesser requested changes
@jhnnsnk Thanks! I just have minor suggestions.
@jessica-mitchell Can you review this PR as soon as possible for inclusion on 3.7?
@terhorstd Adding this to the 3.7 milestone, it is only documentation but important documentation.

2024-04-04 14:08 UTC, jhnnsnk commented on doc/htmldoc/synapses/connectivity_concepts.rst
> +.. The same article also introduces a graphical notation for neuronal network diagrams which will be curated in the documentation of :doc:`NEST Desktop <desktop:user/usage-advanced/network-graph>`.
This statement was already prepared such that we can get it in quickly once the graphical notation is in NEST Desktop. This is the case now and I will include it.

2024-04-04 14:23 UTC, jhnnsnk commented on doc/htmldoc/synapses/connection_generator.rst
> +generator interface and randomly connects 10% of the neurons from
Fixed.

2024-04-04 14:47 UTC, heplesser approved these changes

2024-04-04 14:56 UTC, jessica-mitchell commented
> @jessica-mitchell Can you review this PR as soon as possible for inclusion on 3.7? 

yep will look at it tonight

2024-04-05 07:27 UTC, jessica-mitchell approved these changes

2024-04-05 08:03 UTC, merged