Update README on GitHub
nest/nest-simulator pull request #3277
Opened 2024-08-06 09:36 UTC by jessica-mitchell

This PR updates the README since much of the information is redundant and we can point to documentation for more details. Some parts like citation and contribution are also available in the docs but it seems appropriate to keep some of this info here.

Fixes #2939

2024-08-26 13:18 UTC, terhorstd requested changes
Some smaller changes that could be considered. Not a strong requirement though. If there are reasons against this, of course feel free to reject them, or improve the language constructs where necessary.

2024-08-26 13:18 UTC, terhorstd commented on README.md
> +For working with NEST code and documentation, [see our documentation](https://nest-simulator.readthedocs.io/en/stable/developer_space/index.html#contribute-to-nest)
Also here we could add more links, especially to highlight the non-documentation channels, too.
```suggestion
NEST is built on an active community and we welcome everyone on [our mailinglist](https://nest-simulator.org/mailinglist) with comments and questions.

For documentation improvements, feature requests, bug reports or other issues you can create a [GitHub issue](https://github.com/nest/nest-simulator/issues/new/choose) which will be discussed in our fortnightly [meetings](https://nest-simulator.org/videoconference).

Active contributions to our code and documentation are highly regarded and you can find important steps for working with NEST code and documentation in our [contribute-to-nest documentation](https://nest-simulator.readthedocs.io/en/stable/developer_space/index.html#contribute-to-nest)
```

2024-08-27 07:22 UTC, jessica-mitchell commented on README.md
> +* NEST has a large community of experienced developers and users; NEST was first released in 1994 under the name SYNOD, and has been extended and improved ever since
I don't think so - but I have to double check 
The `/documentation` already goes to stable

2024-12-09 15:30 UTC, terhorstd approved these changes
Thanks for the work and the enduring push on this.
The text looks much better!

2024-12-09 15:30 UTC, merged