Update MAM benchmark on website
nest/nest-simulator pull request #3358
Opened 2024-11-05 14:00 UTC by mlober

This PR corrects the benchmark results for the multi-area model with NEST 3.8 on the NEST website. It separates the strong scaling plot into ground and metastable state.

2024-11-05 15:10 UTC, jessica-mitchell commented
Link to Read the docs build: https://nest-simulator--3358.org.readthedocs.build/en/3358/benchmark_results.html

2024-11-05 15:11 UTC, jessica-mitchell requested changes
Images are not rendering- I think it's the lack of new line, added it as suggestion

2024-11-05 15:11 UTC, jessica-mitchell commented on doc/htmldoc/benchmark_results.rst
> +       Dynamical regime: Metastable state
```suggestion
       Dynamical regime: Metastable state
       
```

2024-11-05 15:11 UTC, jessica-mitchell commented on doc/htmldoc/benchmark_results.rst
> +       Dynamical regime: Ground state
```suggestion
       Dynamical regime: Ground state
       
```

2024-12-09 09:07 UTC, jessica-mitchell approved these changes

2024-12-09 11:49 UTC, ackurth approved these changes
lgtm

2024-12-09 12:03 UTC, merged