Update instances of conda with mamba in docs
nest/nest-simulator pull request #3370
Opened 2024-11-19 09:34 UTC by jessica-mitchell

This PR updates the uses of 'conda' with 'mamba' (not including conda-forge).
The internal requirements for FZJ have changed regarding Anaconda and to mitigate issues we update the docs 
to use Mamba instead.
Some text was removed so there's less confusion between Conda and Mamba.

2024-11-19 10:28 UTC, steffengraber requested changes
Great job. Only a few changes from my side.

2024-11-19 10:28 UTC, steffengraber commented on doc/htmldoc/developer_space/guidelines/mailing_list_guidelines.rst
> +      * relevant system and version information (e.g.,  Ubuntu 22.04/ NEST 3.5 installed using the conda-forge package).
Maybe use NEST 3.8 instead of NEST 3.5

2024-11-25 08:30 UTC, jessica-mitchell commented on doc/htmldoc/developer_space/guidelines/mailing_list_guidelines.rst
> +      * relevant system and version information (e.g.,  Ubuntu 22.04/ NEST 3.5 installed using the conda-forge package).
```suggestion
      * relevant system and version information (e.g.,  Ubuntu 22.04/ NEST 3.8 installed using the conda-forge package).
```

2024-11-25 08:30 UTC, jessica-mitchell commented on doc/htmldoc/installation/condaenv_install.rst
> +* Configure NEST. Add the cmake option ``-CDMAKE_INSTALL_PREFIX:PATH=$MAMBA_PREFIX`` to link nest to your active mamba environment.
```suggestion
* Configure NEST. Add the cmake option ``-CDMAKE_INSTALL_PREFIX:PATH=$CONDA_PREFIX`` to link nest to your active mamba environment.
```

2024-11-25 08:31 UTC, jessica-mitchell commented on doc/htmldoc/installation/condaenv_install.rst
> +   cmake -DCMAKE_INSTALL_PREFIX:PATH=$MAMBA_PREFIX </path/to/NEST/src>
```suggestion
   cmake -DCMAKE_INSTALL_PREFIX:PATH=$CONDA_PREFIX </path/to/NEST/src>
```

2024-11-25 08:31 UTC, jessica-mitchell commented on doc/htmldoc/installation/mac_install.rst
> +which you can install them, e.g., Conda-forge, Homebrew, or MacPorts. The most important
```suggestion
which you can install them, e.g., conda-forge, Homebrew, or MacPorts. The most important
```

2024-11-26 06:34 UTC, steffengraber approved these changes
:+1:

2024-12-09 09:10 UTC, jessica-mitchell commented
Merge as ci fail is unrelated to docs

2024-12-09 09:11 UTC, merged